import { chromium } from 'playwright';
const [base, out] = process.argv.slice(2);
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
page.on('pageerror', (e) => console.log('pageerror:', e.message));
page.on('console', (m) => { if (m.type() === 'error') console.log('console:', m.text().slice(0, 200)); });
const shot = async (n, w = 1200) => { await page.waitForTimeout(w); await page.screenshot({ path: `${out}-${n}.png` }); };
await page.goto(base);
await shot('title', 2500);
await page.mouse.click(800, 450);
await shot('starter', 2000);
await page.getByText('深海の王').click();
await shot('starter2', 800);
await page.getByText('で冒険をはじめる').click();
await shot('home', 2500);
await page.getByText('バトル', { exact: true }).first().click();
await shot('rivals', 1800);
await page.getByText('もどる').click();
await page.waitForTimeout(600);
await page.getByText('デッキ編集', { exact: true }).first().click();
await shot('deck', 2000);
await page.getByText('もどる').click();
await page.waitForTimeout(600);
await page.getByText('コレクション', { exact: true }).first().click();
await shot('collection', 2200);
await page.getByText('もどる').click();
await page.waitForTimeout(600);
await page.getByText('パック開封', { exact: true }).first().click();
await shot('shop', 1800);
await page.getByText('で1パック開ける').click();
await shot('pack-tear', 1500);
await page.locator('.opening .pack').click();
await shot('pack-reveal0', 1500);
for (let i = 0; i < 20; i++) { await page.locator('.reveal-card').click().catch(() => {}); await page.waitForTimeout(700); if (await page.locator('.summary').count()) break; if (i === 17) await shot('pack-last', 300); }
await shot('pack-summary', 1500);
await browser.close();
