import type { ActionDef, CharacterDef, HitWindow } from '../combat/types';

const rushHits: HitWindow[] = [];
for (let i = 0; i < 10; i++) {
  rushHits.push({
    start: 14 + i * 5,
    end: 16 + i * 5,
    damage: 15,
    knockback: 1.2,
    knockUp: 0.4,
    hitstun: 22,
    hitstop: 2,
    range: 1.6,
    radius: 1.05,
    pull: true,
    hand: i % 2 === 0 ? 'L' : 'R',
  });
}
rushHits.push({
  start: 70,
  end: 75,
  damage: 160,
  knockback: 18,
  knockUp: 15,
  hitstun: 40,
  hitstop: 16,
  range: 1.6,
  radius: 1.15,
  heavy: true,
  guardDamage: 100,
  hand: 'R',
});

const actions: Record<string, ActionDef> = {
  jabL: {
    id: 'jabL',
    kind: 'attack',
    anim: 'jabL',
    total: 20,
    hits: [{ start: 5, end: 8, damage: 38, knockback: 3.5, knockUp: 1, hitstun: 16, hitstop: 4, range: 1.5, radius: 0.8, hand: 'L', guardDamage: 10 }],
    motion: [{ start: 0, end: 8, forward: 4, magnet: true }],
    comboNext: 'jabR',
    comboFrom: 8,
    moveScale: 0.35,
  },
  jabR: {
    id: 'jabR',
    kind: 'attack',
    anim: 'jabR',
    total: 22,
    hits: [{ start: 5, end: 8, damage: 42, knockback: 4, knockUp: 1, hitstun: 18, hitstop: 5, range: 1.55, radius: 0.8, hand: 'R', guardDamage: 12 }],
    motion: [{ start: 0, end: 8, forward: 4.5, magnet: true }],
    comboNext: 'hook',
    comboFrom: 9,
    moveScale: 0.35,
  },
  hook: {
    id: 'hook',
    kind: 'attack',
    anim: 'hook',
    total: 38,
    hits: [{ start: 12, end: 16, damage: 85, knockback: 10, knockUp: 6, hitstun: 26, hitstop: 9, range: 1.7, radius: 0.95, hand: 'L', heavy: true, guardDamage: 30 }],
    motion: [{ start: 6, end: 15, forward: 7, magnet: true }],
    moveScale: 0.15,
  },
  airPunch: {
    id: 'airPunch',
    kind: 'attack',
    anim: 'airPunch',
    total: 28,
    hits: [{ start: 7, end: 12, damage: 60, knockback: 8, knockUp: 3, hitstun: 22, hitstop: 7, range: 1.6, radius: 0.95, hand: 'R', guardDamage: 20 }],
    motion: [{ start: 4, end: 12, forward: 6, magnet: true }],
    moveScale: 0.5,
  },
  rocketStraight: {
    id: 'rocketStraight',
    kind: 'skill',
    anim: 'rocketStraight',
    total: 44,
    hits: [{ start: 10, end: 24, damage: 95, knockback: 12.5, knockUp: 5, hitstun: 28, hitstop: 10, range: 1.4, radius: 1.0, hand: 'R', heavy: true, guardDamage: 45 }],
    motion: [{ start: 9, end: 24, forward: 22, magnet: true }],
    moveScale: 0,
  },
  // Air Space: rising uppercut that doubles as an edge recovery.
  risingUpper: {
    id: 'risingUpper',
    kind: 'attack',
    anim: 'risingUpper',
    total: 36,
    hits: [{ start: 4, end: 16, damage: 55, knockback: 5, knockUp: 13, hitstun: 26, hitstop: 6, range: 1.1, radius: 1.05, hand: 'R', guardDamage: 20 }],
    motion: [{ start: 2, end: 16, forward: 4, up: 15 }],
    invuln: [0, 6],
    moveScale: 0.6,
  },
  // Click during a dash: shoulder-first charging straight.
  dashStraight: {
    id: 'dashStraight',
    kind: 'attack',
    anim: 'dashStraight',
    total: 30,
    hits: [{ start: 4, end: 11, damage: 60, knockback: 11, knockUp: 5, hitstun: 24, hitstop: 8, range: 1.4, radius: 0.95, hand: 'R', heavy: true, guardDamage: 25 }],
    motion: [{ start: 0, end: 10, forward: 16, magnet: true }],
    moveScale: 0,
  },
  burstRush: {
    id: 'burstRush',
    kind: 'ult',
    anim: 'burstRush',
    total: 96,
    hits: rushHits,
    motion: [{ start: 0, end: 12, forward: 15, magnet: true }],
    moveScale: 0,
    committed: true,
    armor: true,
    invuln: [0, 14],
  },
};

export const blaze: CharacterDef = {
  id: 'blaze',
  name: 'ブレイズ',
  title: '烈火のインファイター',
  weapon: 'fists',
  archetype: 'melee',
  element: { color: 0xff5a1f, color2: 0xffc23d },
  recovery: 'risingUpper',
  dashAttack: 'dashStraight',
  maxHp: 1000,
  walkSpeed: 7.6,
  jumpSpeed: 11.5,
  preferredRange: [0, 1.8],
  skillCooldown: 240,
  actions,
  basic: 'jabL',
  skill: 'rocketStraight',
  ult: 'burstRush',
  airBasic: 'airPunch',
  look: {
    skin: 0xffd2b0,
    hair: 0x7a4426,
    top: 0xe8463c,
    topAccent: 0xffffff,
    pants: 0xd63c2e,
    shoes: 0xffffff,
    glove: 0x2b2b3d,
    eyes: 0x6b3a1e,
    hairStyle: 'ponytail',
    body: 'female',
    hairModel: 'hairParted',
    outfit: { set: 'peasant', parts: ['body', 'arms', 'legs', 'feet'] },
  },
};
