import type { ActionDef, CharacterDef, HitWindow } from '../combat/types';

const spinHits: HitWindow[] = [0, 7, 14, 21].map((s) => ({
  start: 4 + s,
  end: 9 + s,
  area: true,
  range: 0,
  radius: 1.7,
  damage: 12,
  knockback: 3,
  knockUp: 7,
  hitstun: 18,
  hitstop: 3,
  hand: 'R' as const,
  guardDamage: 6,
}));

const actions: Record<string, ActionDef> = {
  swingA: {
    id: 'swingA',
    kind: 'attack',
    anim: 'swingA',
    total: 26,
    hits: [{ start: 7, end: 11, damage: 58, knockback: 5, knockUp: 1.5, hitstun: 18, hitstop: 6, range: 1.9, radius: 1.05, hand: 'R', guardDamage: 14 }],
    motion: [{ start: 0, end: 9, forward: 4, magnet: true }],
    comboNext: 'swingB',
    comboFrom: 12,
    moveScale: 0.3,
  },
  swingB: {
    id: 'swingB',
    kind: 'attack',
    anim: 'swingB',
    total: 28,
    hits: [{ start: 8, end: 12, damage: 62, knockback: 6, knockUp: 2, hitstun: 20, hitstop: 7, range: 1.9, radius: 1.05, hand: 'R', guardDamage: 16 }],
    motion: [{ start: 0, end: 10, forward: 4.5, magnet: true }],
    comboNext: 'smash',
    comboFrom: 13,
    moveScale: 0.3,
  },
  // Combo finisher: overhead "PIKO!" with a small shockwave.
  smash: {
    id: 'smash',
    kind: 'attack',
    anim: 'smash',
    total: 46,
    hits: [
      { start: 16, end: 20, damage: 100, knockback: 12, knockUp: 9, hitstun: 30, hitstop: 12, range: 2.0, radius: 1.3, hand: 'R', heavy: true, guardDamage: 45 },
      { start: 18, end: 21, area: true, range: 2.0, radius: 2.1, damage: 25, knockback: 6, knockUp: 6, hitstun: 20, hitstop: 4 },
    ],
    motion: [{ start: 6, end: 16, forward: 5, magnet: true }],
    moveScale: 0.1,
  },
  // Air click: slam straight down.
  airSmash: {
    id: 'airSmash',
    kind: 'attack',
    anim: 'airSmash',
    total: 34,
    hits: [{ start: 8, end: 26, damage: 70, knockback: 7, knockUp: 2, hitstun: 24, hitstop: 9, range: 1.4, radius: 1.25, hand: 'R', heavy: true, guardDamage: 25 }],
    motion: [{ start: 6, end: 26, forward: 3, up: -20 }],
    landCancel: true,
    moveScale: 0.2,
  },
  // Air Space: helicopter spin that lifts and hits all around (edge recovery).
  heliSpin: {
    id: 'heliSpin',
    kind: 'attack',
    anim: 'heliSpin',
    total: 40,
    hits: spinHits,
    motion: [{ start: 0, end: 30, forward: 5, up: 10, lift: 4.5 }],
    moveScale: 0.8,
  },
  // Click during a dash: charging swing.
  pikoDash: {
    id: 'pikoDash',
    kind: 'attack',
    anim: 'pikoDash',
    total: 34,
    hits: [{ start: 8, end: 14, damage: 65, knockback: 12, knockUp: 6, hitstun: 26, hitstop: 9, range: 1.8, radius: 1.15, hand: 'R', heavy: true, guardDamage: 30 }],
    motion: [{ start: 0, end: 12, forward: 15, magnet: true }],
    moveScale: 0,
  },
  // E: ground pound: a shockwave around Piko plus three waves running along the floor.
  groundPound: {
    id: 'groundPound',
    kind: 'skill',
    anim: 'groundPound',
    total: 50,
    hits: [{ start: 18, end: 22, area: true, range: 0.8, radius: 2.6, damage: 60, knockback: 12, knockUp: 10, hitstun: 30, hitstop: 12, heavy: true, guardDamage: 40 }],
    // Three shockwaves race forward along the floor and pop the target up.
    spawns: [{ frame: 20, hand: 'R', from: 'ground', visual: 'wave', count: 3, fan: 0.45, speed: 16, radius: 0.9, life: 45, damage: 45, knockback: 6, knockUp: 9, hitstun: 24, hitstop: 6, guardDamage: 20 }],
    armor: true,
    moveScale: 0,
  },
  // Q: the hammer grows huge for one giant blow.
  gigaPiko: {
    id: 'gigaPiko',
    kind: 'ult',
    anim: 'gigaPiko',
    total: 92,
    hits: [
      { start: 42, end: 48, damage: 180, knockback: 21, knockUp: 14, hitstun: 40, hitstop: 18, range: 2.8, radius: 2.4, hand: 'R', heavy: true, guardDamage: 100 },
      { start: 44, end: 48, area: true, range: 2.8, radius: 5, damage: 40, knockback: 10, knockUp: 8, hitstun: 26, hitstop: 6 },
    ],
    motion: [{ start: 30, end: 42, forward: 5, magnet: true }],
    moveScale: 0,
    committed: true,
    armor: true,
    invuln: [0, 12],
  },
};

export const piko: CharacterDef = {
  id: 'piko',
  name: 'ピコ',
  title: 'ピコピコハンマーの怪力娘',
  weapon: 'hammer',
  archetype: 'melee',
  element: { color: 0xff4f8b, color2: 0xffe14a },
  recovery: 'heliSpin',
  dashAttack: 'pikoDash',
  maxHp: 1150,
  walkSpeed: 7.0,
  jumpSpeed: 11,
  preferredRange: [0, 2.4],
  skillCooldown: 300,
  actions,
  basic: 'swingA',
  skill: 'groundPound',
  ult: 'gigaPiko',
  airBasic: 'airSmash',
  look: {
    skin: 0xffd9c0,
    hair: 0xff8fb8,
    top: 0xffd84a,
    topAccent: 0xff4f8b,
    pants: 0x6f5bd6,
    shoes: 0xff4f8b,
    glove: 0xffffff,
    eyes: 0xff4f8b,
    hairStyle: 'spiky',
    body: 'female',
    hairModel: 'hairBuns',
  },
};
