import type { ActionDef, CharacterDef, Spawn } from '../combat/types';

/** Suction-cup grapple: sticks to terrain or the opponent and reels Zip in. */
const hook = (frame: number, extra: Partial<Spawn> = {}): Spawn => ({
  frame,
  hand: 'R',
  speed: 44,
  radius: 0.45,
  life: 38,
  visual: 'hook',
  hook: 'self',
  damage: 22,
  knockback: 0,
  knockUp: 1,
  hitstun: 22,
  hitstop: 4,
  guardDamage: 6,
  ...extra,
});

const actions: Record<string, ActionDef> = {
  // Click x3: left jab, launcher-butt cross, rising left hook.
  zJab: {
    id: 'zJab',
    kind: 'attack',
    anim: 'zJab',
    total: 18,
    hits: [{ start: 4, end: 7, damage: 32, knockback: 2.5, knockUp: 0.5, hitstun: 15, hitstop: 4, range: 1.4, radius: 0.85, hand: 'L', guardDamage: 8 }],
    motion: [{ start: 0, end: 6, forward: 4, magnet: true }],
    comboNext: 'zCross',
    comboFrom: 8,
    moveScale: 0.4,
  },
  zCross: {
    id: 'zCross',
    kind: 'attack',
    anim: 'zCross',
    total: 22,
    hits: [{ start: 5, end: 9, damage: 40, knockback: 3.5, knockUp: 1, hitstun: 17, hitstop: 5, range: 1.5, radius: 0.9, hand: 'R', guardDamage: 10 }],
    motion: [{ start: 0, end: 7, forward: 4.5, magnet: true }],
    comboNext: 'zUpper',
    comboFrom: 10,
    moveScale: 0.35,
  },
  zUpper: {
    id: 'zUpper',
    kind: 'attack',
    anim: 'zUpper',
    total: 34,
    hits: [{ start: 9, end: 14, damage: 75, knockback: 8, knockUp: 10, hitstun: 26, hitstop: 9, range: 1.5, radius: 1.0, hand: 'L', heavy: true, guardDamage: 28 }],
    motion: [{ start: 5, end: 13, forward: 6, magnet: true }],
    moveScale: 0.15,
  },
  zAirPunch: {
    id: 'zAirPunch',
    kind: 'attack',
    anim: 'zAirPunch',
    total: 26,
    hits: [{ start: 6, end: 11, damage: 52, knockback: 7, knockUp: 2, hitstun: 20, hitstop: 6, range: 1.5, radius: 0.95, hand: 'L', guardDamage: 18 }],
    motion: [{ start: 3, end: 11, forward: 6, magnet: true }],
    moveScale: 0.5,
  },
  // E (ground or air): fire the hook where you aim.
  hookShot: {
    id: 'hookShot',
    kind: 'skill',
    anim: 'hookShot',
    total: 22,
    spawns: [hook(5)],
    moveScale: 0.6,
    upperBody: true,
  },
  // Air Space: the same hook as an edge recovery (once per airtime).
  hookAir: {
    id: 'hookAir',
    kind: 'attack',
    anim: 'hookShot',
    total: 22,
    spawns: [hook(4)],
    moveScale: 0.6,
  },
  // Click during a dash: flying drop kick.
  dropKick: {
    id: 'dropKick',
    kind: 'attack',
    anim: 'dropKick',
    total: 32,
    hits: [{ start: 4, end: 12, damage: 62, knockback: 12, knockUp: 5, hitstun: 24, hitstop: 8, range: 1.4, radius: 1.0, hand: 'B', heavy: true, guardDamage: 25 }],
    motion: [{ start: 0, end: 12, forward: 18, up: 3, magnet: true }],
    moveScale: 0,
  },
  // Q: a giant hook that reels the opponent in for a launcher uppercut.
  reelIn: {
    id: 'reelIn',
    kind: 'ult',
    anim: 'reelIn',
    total: 44,
    spawns: [hook(12, { hook: 'yank', onHit: 'reelFinisher', speed: 52, life: 42, radius: 0.75, size: 1.8, damage: 40, hitstun: 50, hitstop: 10, guardDamage: 40 })],
    committed: true,
    invuln: [0, 12],
    moveScale: 0,
  },
  reelFinisher: {
    id: 'reelFinisher',
    kind: 'attack',
    anim: 'reelFinisher',
    total: 70,
    hits: [{ start: 8, end: 46, damage: 160, knockback: 18, knockUp: 15, hitstun: 40, hitstop: 18, range: 1.4, radius: 1.5, hand: 'L', heavy: true, guardDamage: 100 }],
    committed: true,
    armor: true,
    moveScale: 0,
  },
};

export const zip: CharacterDef = {
  id: 'zip',
  name: 'ジップ',
  title: '空翔けるフック使い',
  weapon: 'grapple',
  archetype: 'melee',
  element: { color: 0xff8a1f, color2: 0x2fd0ff },
  recovery: 'hookAir',
  dashAttack: 'dropKick',
  maxHp: 1000,
  walkSpeed: 7.5,
  jumpSpeed: 11.5,
  preferredRange: [0, 1.9],
  skillCooldown: 110,
  actions,
  basic: 'zJab',
  skill: 'hookShot',
  ult: 'reelIn',
  airBasic: 'zAirPunch',
  look: {
    skin: 0xc98d62,
    hair: 0x2b1d14,
    top: 0xff8a1f,
    topAccent: 0x2fd0ff,
    pants: 0x3a4250,
    shoes: 0x2fd0ff,
    glove: 0x2b2b3d,
    eyes: 0x2b1d14,
    hairStyle: 'spiky',
    body: 'male',
    hairModel: 'hairBuzzed',
  },
};
