// 第一幕「旅立ち」 — ティム / マリナ / ヴェイン
import { bg, bgm, cg, choice, cutin, fx, hide, mood, move, narr, place, say, show, showCard, shout, sfx, think, title, tone, weather, whisper } from './dsl';
import type { Act, Chapter } from './types';

export const ACT1: Act = { no: 1, title: '旅立ち', sub: '十二枚の伝説', bg: 'story/p-farmer' };

export const ACT1_CHAPTERS: Chapter[] = [
  // ------------------------------------------------------------------ 1 ティム
  {
    id: 'n01',
    act: 1,
    rival: 'tim',
    title: '形見のカード',
    summary: '最初の村。伝説の一枚を持っていたのは、亡き父の形見を握りしめた少年だった。',
    art: 'story/p-farmer',
    before: [
      bgm('knolls'),
      bg('story/landscape-hills-02', 'right'),
      weather('motes'),
      place('ヘイルの村', 'リーフェルから東へ二日'),
      show('hero', 'L', 'normal'),
      narr('最初の手がかりは、麦と羊の村、ヘイル。'),
      narr('宿の主人が言うには、伝説のカードを持っているのは、村はずれに住む子どもだという。'),
      bg('story/p-farmer', 'in'),
      show('tim', 'R', 'normal', 'fade'),
      say('tim', 'だれ？ ……カードの人？ また来たの？'),
      say('hero', 'また？'),
      say('tim', '先月も来たよ。黒い服の人。お金いっぱい出すから売れって。……追い返したけど。'),
      think('hero', '……ほかにも、十二枚を探している人がいる？'),
      say('hero', '{name}っていうんだ。伝説のカードを、バトルで譲ってもらいたくて来た。'),
      mood('tim', 'normal'),
      say('tim', '……やだ。'),
      narr('少年は、胸元の革袋を両手でぎゅっと押さえた。'),
      say('tim', 'これ、父ちゃんのなんだ。去年、山で崖から落ちて……これだけ、ポケットに残ってた。'),
      mood('hero', 'worry'),
      say('hero', '……そっか。'),
      say('tim', 'でも……掟は知ってる。父ちゃんがいつも言ってた。「伝説のカードは、勝った人のもの」って。'),
      say('tim', 'だから、勝負なら受けるよ。ぼくが勝ったら、二度と来ないで。'),
      choice('ティムに、なんと言う？', [
        { label: '「わかった。本気でいく」', then: [mood('hero', 'normal'), say('hero', 'わかった。手加減はしない。それが、きみのお父さんへの礼儀だと思うから。'), say('tim', '……うん。')] },
        { label: '「……本当に、いいのか」', then: [mood('hero', 'worry'), say('hero', '……本当に、いいのか。'), say('tim', 'いいって言ってるだろ！ 父ちゃんのカード、なめるなよ！')] },
      ]),
      bgm('battle1'),
      sfx('horn-1', 0.5),
      shout('tim', '父ちゃん、見ててね！'),
    ],
    after: [
      bgm('sad'),
      bg('story/p-farmer', 'in', { tint: 'rgba(255,190,140,1)' }),
      weather('motes'),
      show('hero', 'L', 'normal'),
      show('tim', 'R', 'normal'),
      narr('最後の一枚がめくられたとき、少年は、しばらく何も言わなかった。'),
      say('tim', '……負けちゃった。'),
      narr('ティムは革袋からカードを抜き、袖で何度もこすってから、差し出した。'),
      showCard('エンシェントウッド', '伝説のカード　二枚目'),
      say('tim', '……父ちゃんのカード、ちゃんと使ってよ。負けたら、許さないから。'),
      mood('hero', 'worry'),
      say('hero', '……約束する。'),
      hide('tim'),
      narr('村を出るとき、振り返ると、少年はまだ畑の端に立っていた。泣いているのかどうかは、遠くてわからなかった。'),
      think('hero', '勝てば、手に入る。……そのたびに、誰かが何かを失う。'),
      think('hero', 'これを、あと十回。'),
    ],
    lose: [
      bg('story/p-farmer', 'in'),
      show('tim', 'C'),
      say('tim', '……まだやるの？ 父ちゃんのカードは、強いんだからね。'),
    ],
  },

  // ------------------------------------------------------------------ 2 マリナ
  {
    id: 'n02',
    act: 1,
    rival: 'marina',
    title: '潮騒の港',
    summary: '港町の海の祠。伝説を守る巫女と、金で動く旅の剣士との出会い。',
    art: 'story/p-new-land',
    before: [
      bgm('journey'),
      bg('story/p-voyage', 'right'),
      weather('none'),
      place('港町ポルトマーレ', '東の海岸'),
      sfx('water-blast', 0.25),
      show('hero', 'L', 'normal'),
      narr('潮の匂い。帆をたたんだ船が、何十隻も並んでいる。'),
      narr('二枚目の手がかりは、町の外れの岬にある「海の祠」。'),
      sfx('sword-1', 0.5),
      fx('shake'),
      narr('——路地に入ったとき、背後で鋼の音がした。'),
      bg('story/landscape-coast', 'in', { tint: 'rgba(200,210,230,1)' }),
      show('bandit', 'R', 'normal', 'drop'),
      say('bandit', 'おい、そこの。いいもん持ってるらしいじゃねえか。赤い竜のカードだ。'),
      mood('hero', 'mad'),
      say('hero', '……どうして、それを。'),
      say('bandit', '酒場で噂になってんだよ。「伝説を集めてる、田舎のガキがいる」ってな！'),
      sfx('sword-1', 0.7),
      fx('flash'),
      show('liese', 'C', 'normal', 'slide'),
      narr('男の短剣が、宙を舞った。'),
      say('liese', '昼間から、子どもひとりに大の大人が？ みっともない。'),
      say('bandit', 'て、てめえ……！'),
      say('liese', '次は、指を落とすけど。'),
      hide('bandit'),
      narr('男は舌打ちして、路地の奥へ消えた。'),
      move('liese', 'R'),
      say('liese', 'ケガは？'),
      say('hero', '……ない。助かった。ありがとう。'),
      say('liese', 'リーゼ。旅の剣士。……あんた、伝説を集めてるんだって？', 'glad'),
      say('liese', 'だったら、護衛を雇いなよ。ひとり旅じゃ、今のが毎晩来るよ。安くしとく。'),
      choice('リーゼの申し出に、どう答える？', [
        { label: '「お願いしたい」', then: [mood('hero', 'normal'), say('hero', '……お願いしたい。正直、助かる。'), say('liese', '決まり。前払いで半分ね。', 'glad')] },
        { label: '「どうして自分に？」', then: [mood('hero', 'worry'), say('hero', 'どうして、自分に声をかけたの。'), say('liese', '金になりそうだから。それ以外に理由がいる？'), say('hero', '……正直なんだな。じゃあ、お願いするよ。')] },
      ]),
      narr('このとき、彼女が一瞬だけ目をそらしたことに、気づかなかった。'),

      bgm('silence'),
      fx('fadeBlack'),
      bg('story/p-wild-sea', 'in', { tint: 'rgba(150,190,220,1)' }),
      weather('rain'),
      fx('unfade'),
      place('海の祠', '岬の先'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('marina', 'R', 'normal', 'rise'),
      narr('波しぶきの向こう、岩の上の小さな祠に、ひとりの人魚が座っていた。'),
      say('marina', '……来ると思っていた。海が、ずっと騒いでいたから。'),
      say('marina', 'あなたが探しているカードは、ここにある。でも、ひとつだけ教えてあげる。'),
      say('marina', 'このカードを手にした者は、みんな不幸になった。漁師も、商人も、私の母も。'),
      say('marina', '海は、欲を連れていくの。……それでも、望む？'),
      say('hero', '……望む。待っている人がいるんだ。'),
      say('marina', 'そう。……なら、波に聞いてみましょう。'),
      bgm('battle1'),
      sfx('horn-1', 0.5),
      shout('marina', '海よ、この者を試して！'),
    ],
    after: [
      bgm('sad'),
      bg('story/p-wild-sea', 'in', { tint: 'rgba(150,190,220,1)' }),
      weather('rain'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('marina', 'R', 'normal'),
      say('marina', '……波が、あなたを選んだのね。'),
      showCard('リヴァイアサーペント', '伝説のカード　三枚目'),
      say('marina', '持っていって。そして、できれば……途中で、手放して。'),
      say('hero', '……どういう意味？'),
      say('marina', '十二枚を揃えた人の話は、どの物語でも、最後まで書かれていないの。'),
      hide('marina'),
      sfx('water-blast', 0.3),
      narr('人魚は、静かに海へ消えた。'),
      say('liese', '……気味の悪い話。さ、次へ行こ。日が暮れる前に峠を越えたい。'),
      narr('その夜。宿の窓辺で、リーゼが小さな紙を鳩の足に結んでいるのを、ぼんやりと見ていた。'),
      say('hero', '手紙？'),
      say('liese', '……家族に。元気だよって、それだけ。', 'normal'),
    ],
    lose: [
      bg('story/p-wild-sea', 'in', { tint: 'rgba(150,190,220,1)' }),
      show('marina', 'C'),
      say('marina', '波は、まだ引いていない。……もう一度、来るのね。'),
    ],
  },

  // ------------------------------------------------------------------ 3 ヴェイン
  {
    id: 'n03',
    act: 1,
    rival: 'vane',
    title: '雷鳴の峠',
    summary: 'カードの賭けで兄を亡くした射手。「そんなもののために、人は死ぬんだ」。',
    art: 'story/p-escape',
    before: [
      bgm('suspense'),
      bg('story/landscape-mountains-04', 'up'),
      weather('storm'),
      place('雷鳴の峠', '東の山道'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('峠に雷が落ちる。三枚目の持ち主は、この山小屋に住む射手だという。'),
      sfx('lightning', 0.5),
      fx('flash'),
      narr('——目の前の岩に、矢が突き立った。'),
      show('vane', 'R', 'normal', 'drop'),
      say('vane', 'それ以上来るな。カード遊びの連中は、ここじゃ歓迎されない。'),
      say('hero', '伝説のカードの持ち主に、バトルを申し込みに来た。'),
      say('vane', '……ハッ。やっぱりか。'),
      say('vane', '教えてやろうか。俺の兄貴はな、カードに取り憑かれた。'),
      tone('sepia'),
      bgm('sad'),
      cg('story/p-mourning', 'in', '三年前'),
      narr('畑を賭け、家を賭け、最後には母の形見の指輪まで賭けた。'),
      narr('そして、全部負けた。'),
      whisper('vane', '……納屋で、首を吊ってたよ。足元に、カードが散らばってた。'),
      cg(null),
      tone('none'),
      bgm('suspense'),
      say('vane', '兄貴を負かした男から、俺がこの一枚を取り返した。……誰にも渡すつもりはない。'),
      mood('liese', 'mad'),
      say('liese', 'でも、掟は掟でしょ。バトルを挑まれて逃げるのは、あんたの兄さんより格好悪いんじゃない？'),
      say('vane', '……なんだと。'),
      mood('hero', 'mad'),
      say('hero', 'リーゼ！'),
      say('vane', '……いいだろう。乗ってやる。'),
      say('vane', 'その代わり、俺が勝ったら、おまえのカードを全部、この崖から捨てる。'),
      cutin('vane', 'normal', 'カードなんか、全部燃えちまえ'),
      bgm('battle2'),
      sfx('lightning', 0.6),
      shout('vane', '来い、遊び人！'),
    ],
    after: [
      bgm('elegy'),
      bg('story/landscape-mountains-04', 'in', { tint: 'rgba(160,170,200,1)' }),
      weather('rain'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('vane', 'R', 'normal'),
      narr('雨が、雷を連れて遠ざかっていく。'),
      say('vane', '……持っていけ。'),
      showCard('ハリケーンドレイク', '伝説のカード　四枚目'),
      say('vane', 'そんなもんのために、人は死ぬんだ。おまえの師匠だって、そうならないとは限らない。'),
      mood('hero', 'worry'),
      say('hero', '……先生は、病気を治したいだけだ。'),
      say('vane', '病気、か。……兄貴も最初は、借金を返したいだけだった。'),
      hide('vane'),
      narr('射手は背を向け、山小屋へ戻っていった。'),
      mood('liese', 'normal'),
      say('liese', '……さっきは、ごめん。煽るような言い方して。'),
      say('hero', 'いいよ。おかげで、勝負になった。'),
      say('liese', '……そういうとこ、甘いよね。{name}は。', 'glad'),
      title('第一幕　完', '四枚の伝説', 'ACT I'),
    ],
    lose: [
      bg('story/landscape-mountains-04', 'in', { tint: 'rgba(160,170,200,1)' }),
      weather('storm'),
      show('vane', 'C'),
      say('vane', '……その程度か。崖まで、案内してやろうか。'),
    ],
  },
];

