// 第1幕「旅立ちの森」 — ティム / マリナ / ヴェイン / グロム
import { bg, bgm, fx, hide, mood, narr, say, show, shout, sfx, title, weather } from './dsl';
import type { Act, Chapter } from './types';

export const ACT1: Act = { no: 1, title: '旅立ちの森', sub: '黒い霧のはじまり', bg: 'story/landscape-hills-01' };

export const ACT1_CHAPTERS: Chapter[] = [
  // ------------------------------------------------------------------ 1 ティム
  {
    id: 'c01',
    act: 1,
    rival: 'tim',
    title: '村はずれの勝負',
    summary: '森の仲間を自慢する村の少年ティムと、はじめての勝負。',
    before: [
      bgm('menu'),
      title('第一幕　旅立ちの森', '黒い霧のはじまり', 'ACT I'),
      bg('story/landscape-hills-01', 'left'),
      weather('petals'),
      show('alto', 'L', 'glad'),
      narr('村の入り口。朝の光のなかで、ひとりの少年が腕を組んで待っていた。'),
      show('tim', 'R', 'normal', 'drop'),
      shout('tim', 'おそいぞ、アルト！ ぼく、ずーっと待ってたんだ！'),
      say('alto', 'ティム！ もしかして、ぼくの最初の相手って……'),
      say('tim', 'そう、ぼく！ 師匠さんに頼まれたんだ。「本気で相手してやれ」って。'),
      say('tim', 'ぼくの森の仲間たち、すっごく強いんだぞ！'),
      mood('alto', 'normal'),
      say('alto', '手加減はなし、だよね？'),
      say('tim', 'もちろん！ 負けたらアルトの秘密、村じゅうに言いふらすからね！'),
      mood('alto', 'worry'),
      say('alto', 'そ、それはこまる……！'),
      sfx('horn-3', 0.6),
      bgm('battle1'),
      shout('alto', '勝負だ、はじめよう！'),
    ],
    after: [
      bgm('menu'),
      bg('story/landscape-hills-01', 'in'),
      show('alto', 'L', 'glad'),
      show('tim', 'R', 'normal'),
      say('tim', 'うわぁ、負けちゃった……でも、すっごく楽しかった！'),
      mood('alto', 'glad'),
      say('alto', 'ティムの森の仲間、本当に強かったよ。最後までひやひやした。'),
      say('tim', 'えへへ。……ねえ、アルト。ほんとに旅に出るの？'),
      say('alto', 'うん。黒い霧のこと、放っておけないから。'),
      mood('tim', 'normal'),
      say('tim', '……じゃあ、これあげる。森の木の実のお守り。みんなが見守ってくれるって。'),
      sfx('potion', 0.5),
      narr('アルトは小さなお守りをポケットにしまった。'),
      say('tim', 'そうだ、この先の海辺で、霧が出てるって聞いた。気をつけてね！'),
      say('alto', 'ありがとう、ティム。行ってくる！'),
      hide('tim'),
      narr('こうして、アルトの長い旅が始まった。'),
    ],
    lose: [
      bg('story/landscape-hills-01', 'in'),
      show('tim', 'R', 'normal'),
      say('tim', 'えへへ、ぼくの勝ち！ ……あ、ごめん、笑いすぎた？'),
      say('tim', '大丈夫、もう一回やろう！ アルトならきっと勝てるよ！'),
    ],
  },

  // ------------------------------------------------------------------ 2 マリナ
  {
    id: 'c02',
    act: 1,
    rival: 'marina',
    title: '潮騒の社',
    summary: '海辺の社で、海の声を聞く巫女マリナが力を試す。',
    before: [
      bgm('menu'),
      bg('story/landscape-coast', 'right'),
      weather('fog'),
      show('alto', 'L', 'worry'),
      narr('村を出て三日。海辺の街道は、薄い霧にけぶっていた。'),
      say('alto', '波の音が……いつもと違う。うなされてるみたいだ。'),
      show('marina', 'R', 'normal', 'fade'),
      say('marina', '聞こえるのですね、あなたにも。海の声が。'),
      say('alto', 'あなたは？'),
      say('marina', 'マリナ。この社で海に仕える巫女です。……海が、泣いているのです。'),
      say('marina', '黒い霧のせいで、深いところの子たちが眠れずにいる。'),
      say('alto', 'ぼくは、その霧を止める方法をさがしてるんです。力を貸してください。'),
      say('marina', '……言葉だけでは、海は動きません。', 'normal'),
      say('marina', '見せてください。あなたと、あなたの仲間との絆を。'),
      bgm('battle1'),
      sfx('horn-3', 0.6),
      say('marina', '海の声が、あなたを選ぶかどうか——試させてもらうわ。'),
    ],
    after: [
      bgm('menu'),
      bg('story/landscape-coast', 'in'),
      weather('motes'),
      show('alto', 'L', 'glad'),
      show('marina', 'R'),
      say('marina', '見事ね。海もあなたを認めたみたい。'),
      say('marina', '波が、笑っているわ。何年ぶりかしら。'),
      sfx('magic-holy-1', 0.5),
      narr('マリナは小さな巻き貝を、アルトの手にのせた。'),
      say('marina', 'この貝を耳にあてれば、海はいつでもあなたに語りかける。道に迷ったときは、聞いてみて。'),
      say('alto', 'ありがとうございます、マリナさん。'),
      say('marina', '気をつけて。霧は山の方がもっと濃いわ。山道には、雷のような弓の名手がいる……'),
      say('marina', 'きっと、気が立っているはず。'),
      hide('marina'),
    ],
    lose: [
      bg('story/landscape-coast', 'in'),
      show('marina', 'R'),
      say('marina', '波は全てを飲み込むの。……でも、また寄せてくる。あなたも、もう一度どうぞ。'),
    ],
  },

  // ------------------------------------------------------------------ 3 ヴェイン
  {
    id: 'c03',
    act: 1,
    rival: 'vane',
    title: '雷鳴の峠',
    summary: '峠で待ち伏せる雷弓の射手ヴェイン。召喚士を憎む理由とは。',
    before: [
      bgm('menu'),
      bg('story/landscape-mountains-04', 'up'),
      weather('storm'),
      show('alto', 'L', 'worry'),
      narr('山の峠。雷雲が低く垂れこめ、遠くで稲光がはしった。'),
      sfx('lightning', 0.5),
      fx('flash'),
      show('liese', 'FL', 'normal', 'fade'),
      say('liese', 'そこの旅人！ 止まりなさい！ この先は危険です！'),
      say('alto', '騎士……見習いさん？'),
      mood('liese', 'mad'),
      say('liese', '見習いは余計です！ 王都騎士団のリーゼ。この峠の異変を調べに来たのです。'),
      show('vane', 'R', 'normal', 'rise'),
      shout('vane', '動くな。そこの召喚士ども。'),
      say('vane', '俺の村の獣たちが、霧のせいで狂った。……カードだのなんだの、おまえらの商売道具のせいでな。'),
      say('alto', 'ちがう！ 霧のせいなんです。ぼくたちは、それを止めに——'),
      say('vane', '口では何とでも言える。', 'normal'),
      say('vane', '本当に獣と向き合えるやつか、この雷で確かめてやる。'),
      mood('liese', 'normal'),
      say('liese', 'アルト、だったわね。……あなたの勝負、見届けさせてもらうわ。'),
      bgm('battle2'),
      sfx('horn-3', 0.6),
      shout('vane', '目を離すなよ。俺の雷は一瞬だ！'),
    ],
    after: [
      bgm('menu'),
      bg('story/landscape-mountains-04', 'in'),
      weather('none'),
      show('alto', 'L', 'glad'),
      show('liese', 'FL', 'normal'),
      show('vane', 'R'),
      say('vane', '……ちっ、俺の矢が見切られるとはな。'),
      say('vane', '悪かった。霧のなかで暴れてた獣の目を、俺は忘れられなくてな。'),
      say('alto', '分かります。ぼくも、同じ霧を見ました。'),
      mood('vane', 'normal'),
      say('vane', '……あの霧の濃いほうへ、ひとつ道がある。岩山を抜ける近道だ。'),
      say('vane', 'だが、そこには「岩山の戦士」がいる。通すか通さないかは、やつの気分しだいだ。'),
      mood('liese', 'glad'),
      say('liese', '岩山の戦士！ 話に聞いたことがあるわ。面白そうじゃない。'),
      say('liese', 'アルト、私もついて行っていい？ 王都へ報告する前に、あなたの戦いをもっと見たいの。'),
      mood('alto', 'glad'),
      say('alto', 'もちろん！ 心強いよ、リーゼ！'),
      narr('こうして、旅の仲間がひとり増えた。'),
      hide('vane'),
    ],
    lose: [
      bg('story/landscape-mountains-04', 'in'),
      show('vane', 'R'),
      say('vane', '遅い、遅すぎる！ ……もう一度、構えろ。'),
    ],
  },

  // ------------------------------------------------------------------ 4 グロム
  {
    id: 'c04',
    act: 1,
    rival: 'grom',
    title: '岩山の関所',
    summary: '山道をふさぐトロルの戦士グロム。「通りたければ殴り勝て！」',
    before: [
      bgm('menu'),
      bg('story/landscape-mountains-05', 'left'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('岩山の細い山道。巨大な影が、道いっぱいに立ちはだかっていた。'),
      show('grom', 'R', 'normal', 'drop'),
      fx('quake'),
      shout('grom', 'グハハハ！ ここから先は通さんぞ！'),
      say('liese', 'なんて大きさ……！ 話は通じるのかしら。'),
      say('alto', 'あの、通らせてもらいたいんです。事情があって——'),
      say('grom', '事情？ 知らん！ オレ様は強い奴にしか興味がない！'),
      say('grom', '通りたければ、オレ様に勝ってみせろ！ それが岩山の掟だ！'),
      mood('liese', 'mad'),
      say('liese', '……分かりやすくて、助かるわ。'),
      mood('alto', 'glad'),
      say('alto', 'いいですよ、グロムさん。受けて立ちます！'),
      bgm('battle2'),
      sfx('horn-3', 0.6),
      shout('grom', 'グハハハ！ オレ様の拳を受けてみろ！'),
    ],
    after: [
      bgm('menu'),
      bg('story/landscape-mountains-05', 'in'),
      show('alto', 'L', 'glad'),
      show('liese', 'FL', 'glad'),
      show('grom', 'R'),
      say('grom', 'ぐぬぬ……お前、小さいのにやるな！'),
      say('grom', '気に入った！ オレ様の山を通るがいい！ 道案内もしてやる！'),
      say('liese', 'すごいわ、アルト。あの巨体を相手に一歩も引かないなんて。'),
      mood('alto', 'normal'),
      say('alto', 'グロムさんの拳、ほんとに重かったよ……まだ腕がしびれてる。'),
      say('grom', 'グハハ！ 謙遜するな！ ……それにしても、最近の山はおかしい。'),
      say('grom', '霧のせいで、山の仲間がみんな落ちつかん。強いやつがいるなら、霧の出どころを叩きたい。'),
      say('alto', '一緒に行きましょう！ みんなの力が必要なんです。'),
      say('grom', '……グハハハ！ よかろう！ オレ様の力、貸してやる！'),
      fx('flash'),
      sfx('fanfare-short', 0.6),
      narr('岩山の戦士グロムが、頼もしい仲間になった。'),
      narr('山を越えれば、霧の中心へ向かう道が見えてくる——。'),
      hide('grom'),
    ],
    lose: [
      bg('story/landscape-mountains-05', 'in'),
      show('grom', 'R'),
      say('grom', 'グハハ！ 力こそすべて！ ……どうした、もう終わりか？'),
    ],
  },
];
