// 第二幕「奪い合う者たち」 — ロウガ / フローラ / ガルム
import { bars, bg, bgm, cg, choice, cutin, fx, hide, mood, move, narr, place, say, show, showCard, shout, sfx, think, title, tone, wait, weather, whisper } from './dsl';
import type { Act, Chapter } from './types';

export const ACT2: Act = { no: 2, title: '奪い合う者たち', sub: '欲と、嘘と', bg: 'story/p-ambush' };

export const ACT2_CHAPTERS: Chapter[] = [
  // ------------------------------------------------------------------ 4 ロウガ
  {
    id: 'n04',
    act: 2,
    rival: 'rouga',
    title: '狼の街道',
    summary: '旅人からカードと命を奪う野盗の頭。その手下たちの目も、また飢えていた。',
    art: 'story/p-ambush',
    before: [
      title('第二幕　奪い合う者たち', '欲と、嘘と', 'ACT II'),
      bgm('suspense'),
      bg('story/p-midlands', 'right', { tint: 'rgba(210,190,160,1)' }),
      weather('ash'),
      place('灰の街道', '東の平原'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('焼け落ちた馬車が、道ばたに転がっていた。'),
      narr('荷台には、引き裂かれたカード入れ。持ち主の姿は——ない。地面に、黒く乾いた染みだけ。'),
      say('liese', '……見ないほうがいい。'),
      sfx('wolf-growl-3', 0.7),
      fx('shake'),
      narr('遠吠え。四方から。'),
      bg('story/p-ambush', 'in', { tint: 'rgba(200,170,140,1)' }),
      show('bandit', 'FR', 'normal', 'drop'),
      show('rouga', 'R', 'normal', 'slide'),
      cutin('rouga', 'normal', '荷物も、カードも、命もだ'),
      say('rouga', 'へへ……赤い竜のカードの噂は、本当だったか。'),
      say('rouga', '街道は、狼の縄張りだ。通るなら、通行料を払ってもらう。ぜんぶだ。'),
      mood('liese', 'mad'),
      move('liese', 'C'),
      say('liese', '……下がって、{name}。'),
      say('rouga', 'おっと、剣を抜くなよ、姉ちゃん。うしろを見な。'),
      sfx('wolf-growl-1', 0.6),
      narr('振り返ると、狼に乗った子どもたちが、弓を引いていた。十歳にも満たない顔。'),
      say('rouga', '俺のかわいい手下どもだ。親に売られて、俺が拾ってやった。……撃てと言えば、撃つぜ？'),
      mood('hero', 'mad'),
      say('hero', '……バトルで決めよう。伝説の持ち主同士なら、掟がある。'),
      say('rouga', '掟？ ハハッ！ ……まあいい。どうせ勝つのは俺だ。そのあと、ゆっくり身ぐるみ剥がしてやる。'),
      bgm('battle2'),
      shout('rouga', '群れの牙から、逃げられると思うなよ！'),
    ],
    after: [
      bgm('silence'),
      bg('story/p-ambush', 'still', { tint: 'rgba(170,140,120,1)' }),
      weather('ash'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('rouga', 'R', 'normal'),
      say('rouga', '……ちっ。こんな、ガキに。'),
      say('rouga', 'カードはくれてやる。掟だからな。……おい、お前ら、帰るぞ。'),
      narr('誰も、動かなかった。'),
      show('bandit', 'FR', 'normal', 'fade'),
      say('bandit', '……頭。負けたんだろ。'),
      say('rouga', 'なんだ、その目は——'),
      sfx('sword-1', 0.8),
      fx('flashRed'),
      tone('blood'),
      fx('quake'),
      narr('鈍い音がした。'),
      narr('ロウガの胸から、錆びた刃の先が突き出ていた。'),
      whisper('rouga', '……は……育てて、やった、のに……'),
      sfx('wolf-die-1', 0.6),
      hide('rouga'),
      narr('倒れた男の上を、子どもたちの狼が踏み越えていく。誰ひとり、振り返らなかった。'),
      say('bandit', '……カードは、あんたのもんだ。持ってけ。俺たちは、新しい頭の下で生きる。'),
      hide('bandit'),
      tone('none'),
      bgm('elegy'),
      narr('血だまりの中に、一枚のカードが落ちていた。'),
      showCard('グレートウルフ', '伝説のカード　五枚目'),
      mood('hero', 'worry'),
      say('hero', '……どうして。'),
      say('liese', '負けた頭に、ついていく理由はない。……こういう場所じゃ、それが普通なの。'),
      say('liese', '{name}。手、震えてる。'),
      say('hero', '……血を見たのは、初めてなんだ。'),
      narr('リーゼは何も言わず、自分のマントを、そっと肩にかけてくれた。'),
    ],
    lose: [
      bg('story/p-ambush', 'in', { tint: 'rgba(200,170,140,1)' }),
      show('rouga', 'C'),
      say('rouga', 'へへ……もう一回やるか？ 次は、指を一本ずつ賭けてもらおうか。'),
    ],
  },

  // ------------------------------------------------------------------ 5 フローラ
  {
    id: 'n05',
    act: 2,
    rival: 'flora',
    title: '墓守の娘',
    summary: '恋人の棺に、伝説の一枚が眠っている。勝てば、墓を掘り返すことになる。',
    art: 'story/p-graves',
    before: [
      bgm('sad'),
      bg('story/p-graves', 'in', { tint: 'rgba(170,180,200,1)' }),
      weather('fog'),
      place('霧の墓地', '森の奥'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('霧の中に、苔むした墓石が並んでいた。'),
      narr('いちばん新しい墓の前で、ひとりのエルフが花を替えていた。'),
      show('flora', 'R', 'normal', 'fade'),
      say('flora', '……カードのこと？'),
      say('hero', 'どうして、わかった？'),
      say('flora', 'ここに来る生きた人は、みんなそれが目当てだから。'),
      say('flora', '彼は、カードが好きだったの。伝説の一枚を見つけたって、子どもみたいにはしゃいで。'),
      say('flora', '……結婚式の三日前に、熱病で死んだ。'),
      say('flora', 'だから、棺に入れたの。いちばん好きなものと一緒に眠れるように。'),
      mood('hero', 'worry'),
      think('hero', '……墓を、暴くことになる。'),
      choice('どうする？', [
        { label: '「……ほかの方法を探す」', then: [say('hero', '……ほかの方法を探す。こんなの、間違ってる。'), mood('liese', 'mad'), say('liese', '{name}。十二枚、揃えるんでしょ。先生、待ってるんでしょ。'), say('hero', '……。'), say('flora', 'やさしい人ね。でも、ここまで来た人は、みんな最後には同じことを言うの。')] },
        { label: '「バトルを、申し込みたい」', then: [say('hero', '……ごめん。バトルを、申し込みたい。'), say('flora', '……そう。'), say('flora', 'いいわ。私が勝ったら、二度とここへは来ないで。')] },
      ]),
      say('flora', '彼の眠りを、乱さないで。……私に、勝てなければ。'),
      bgm('battle1'),
      sfx('magic-thorns-1', 0.5),
      shout('flora', '森の子たち、彼を守って！'),
    ],
    after: [
      bgm('elegy'),
      bg('story/p-graves', 'still', { tint: 'rgba(120,130,160,1)' }),
      weather('rain'),
      show('hero', 'L', 'normal'),
      show('flora', 'R', 'normal'),
      say('flora', '……掘るなら、せめて、優しくしてあげて。'),
      hide('flora'),
      bars(true),
      fx('fadeBlack'),
      wait(500),
      cg('story/p-remains', 'in', 'その夜'),
      fx('unfade'),
      sfx('mud-glob', 0.4),
      narr('雨の中、ふたりで土を掘った。'),
      narr('棺の蓋は、思ったより軽かった。'),
      narr('半年の土の下で、彼はもう、彼の形をしていなかった。'),
      narr('胸の上で組まれた骨の指が、一枚のカードを、まだ握っていた。'),
      sfx('bat-hit-1', 0.2),
      narr('一本ずつ、指を外した。ぽき、と小さな音がした。'),
      cg(null),
      bars(false),
      showCard('クイーンアント', '伝説のカード　六枚目'),
      mood('hero', 'worry'),
      say('hero', '……ごめんなさい。'),
      narr('誰に謝ったのか、自分でもわからなかった。'),

      bgm('shadows'),
      tone('cold'),
      bg('story/landscape-hills-02', 'still', { tint: 'rgba(90,100,140,1)' }),
      weather('none'),
      place('野営地', '深夜'),
      show('liese', 'C', 'normal', 'fade'),
      narr('眠れなかった。焚き火の向こうで、リーゼが起き上がる気配がした。'),
      narr('彼女は、また小さな紙に何かを書き、闇の中へ鳩を放った。'),
      whisper('liese', '……六枚。あと、半分。'),
      whisper('liese', 'ごめん、{name}。'),
      tone('none'),
    ],
    lose: [
      bg('story/p-graves', 'in', { tint: 'rgba(170,180,200,1)' }),
      weather('fog'),
      show('flora', 'C'),
      say('flora', '……帰って。お願いだから。'),
    ],
  },

  // ------------------------------------------------------------------ 6 ガルム
  {
    id: 'n06',
    act: 2,
    rival: 'garm',
    title: '鉱山の掟',
    summary: '賃金をカードで賭けさせる鉱山の親方。そして、待ち伏せていたのは——。',
    art: 'story/p-fort',
    before: [
      bgm('revenge'),
      bg('story/landscape-mountains-03', 'in', { tint: 'rgba(200,170,140,1)' }),
      weather('ash'),
      place('黒岩の鉱山町', '北の山麓'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('煤で黒く汚れた町。坑道から出てくる男たちの目は、どれも落ちくぼんでいた。'),
      bg('story/blacksmith', 'in'),
      weather('embers'),
      show('garm', 'R', 'normal', 'rise'),
      sfx('ugg', 0.6),
      say('garm', 'よそ者か。賃金がほしけりゃ、勝って取れ。それがこの山の掟だ。'),
      say('hero', '……賃金を、賭けさせてるのか。働いた人たちの。'),
      say('garm', 'グハハ！ 賭けたいと言ってるのは奴らのほうだ。一枚勝てば、ひと月分が倍になる。……負けたことしかないがな。'),
      say('garm', 'で、おまえは何の用だ。伝説のカードか？ 欲しけりゃ、おまえも賭けろ。持ってるカード全部だ。'),
      mood('hero', 'mad'),
      say('hero', '……わかった。そのかわり、自分が勝ったら、今月の賃金を全員に返してもらう。'),
      say('garm', 'ほう？ グハ……グハハハ！ いいぞ、気に入った！'),
      mood('liese', 'normal'),
      say('liese', '……{name}。あんた、ほんとに甘い。'),
      bgm('battle2'),
      shout('garm', '山の掟だ！ 力で語れ！'),
    ],
    after: [
      bgm('suspense'),
      bg('story/blacksmith', 'in', { tint: 'rgba(200,160,120,1)' }),
      weather('embers'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('garm', 'R', 'normal'),
      say('garm', '……グハ。山の掟は、おまえの勝ちだ。賃金は返す。カードも持っていけ。'),
      showCard('トロルジェネラル', '伝説のカード　七枚目'),
      say('garm', 'ひとつ忠告してやる。おまえ、つけられてるぞ。三日前から、町に黒い服の女どもがうろついてる。'),
      mood('hero', 'worry'),
      say('hero', '……黒い服？'),
      hide('garm'),
      sfx('sword-1', 0.7),
      fx('flash'),
      bg('story/p-fort', 'in', { tint: 'rgba(150,140,170,1)' }),
      weather('none'),
      show('agent', 'R', 'normal', 'drop'),
      say('agent', 'お見事。七枚目、確認しました。'),
      say('agent', 'ご苦労さま、リーゼ。……あら、まだ話していなかったの？'),
      bgm('revelation'),
      fx('zoomPunch'),
      mood('hero', 'mad'),
      move('liese', 'C'),
      say('hero', '……リーゼ。どういうこと。'),
      mood('liese', 'hurt'),
      say('liese', '……。'),
      say('agent', '依頼人は、伝説のカードの行方をお知りになりたいの。彼女は、毎晩それを手紙で報告してくれた。いい仕事ぶりよ。'),
      say('agent', '今日はご挨拶だけ。カードには手を出すなと言われているから。……では、また。'),
      hide('agent'),
      wait(600),
      say('hero', '……全部、嘘だったのか。護衛も、手紙も、家族も。'),
      say('liese', '家族は、嘘じゃない！'),
      say('liese', '……弟が、病気なの。薬代が、毎月、とんでもない額で。……どうしても、お金が要った。'),
      choice('リーゼに、なんと言う？', [
        { label: '「……言ってくれれば、よかったのに」', then: [mood('hero', 'worry'), say('hero', '……言ってくれれば、よかったのに。'), say('liese', '言えるわけ、ないでしょ。あんた、すぐ信じるんだもん。')] },
        { label: '「出ていってくれ」', then: [mood('hero', 'mad'), say('hero', '……出ていってくれ。'), say('liese', '……うん。そうだよね。')] },
      ]),
      say('liese', '前払いの残りは、いらない。……じゃあね、{name}。'),
      hide('liese'),
      bgm('sad'),
      weather('rain'),
      narr('雨が降り出した。'),
      narr('マントを返し忘れていたことに気づいたのは、彼女の足音が聞こえなくなってからだった。'),
      title('第二幕　完', '七枚の伝説', 'ACT II'),
    ],
    lose: [
      bg('story/blacksmith', 'in'),
      weather('embers'),
      show('garm', 'C'),
      say('garm', 'グハハ！ 次の給金も俺のもんだ！ ……さあ、もう一回賭けるか？'),
    ],
  },
];

