// 第2幕「紅蓮の山脈」 — イグナス / ロウガ / フローラ / ガルム
import { bg, bgm, fx, hide, mood, narr, say, show, shout, sfx, think, title, weather, whisper } from './dsl';
import type { Act, Chapter } from './types';

export const ACT2: Act = { no: 2, title: '紅蓮の山脈', sub: '燃える空と、荒ぶる獣たち', bg: 'story/landscape-lava' };

export const ACT2_CHAPTERS: Chapter[] = [
  // ------------------------------------------------------------------ 5 イグナス
  {
    id: 'c05',
    act: 2,
    rival: 'ignis',
    title: '竜騎士の火口',
    summary: '火山の火口で待つ竜騎士イグナス。相棒の竜は、霧に苦しんでいた。',
    before: [
      bgm('menu'),
      title('第二幕　紅蓮の山脈', '燃える空と、荒ぶる獣たち', 'ACT II'),
      bg('story/landscape-lava', 'in'),
      weather('embers'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('grom', 'C', 'normal'),
      narr('山脈の奥。大地が赤く脈打ち、空には灰が舞っていた。'),
      say('grom', 'グハハ、あつい！ オレ様の岩肌が焼けるぞ！'),
      say('liese', '無理しないでね、グロム。……あれは、ドレイク？'),
      sfx('drake-hit-1', 0.5),
      fx('quake'),
      hide('grom'),
      show('ignis', 'R', 'normal', 'drop'),
      shout('ignis', '止まれ、旅の者！ これより先は、紅蓮の竜の領域だ。'),
      say('alto', '竜騎士……イグナスさん、ですか？ ぼくたちは霧を止めるために——'),
      say('ignis', '霧、か。……見ろ、我が相棒を。'),
      narr('火口のふちで、巨大な赤い竜がうずくまっていた。その瞳は、ひどく濁っている。'),
      mood('ignis', 'normal'),
      say('ignis', '何日も、苦しんでいる。絆は切れておらぬ。だが、あやつは己を見失いかけている。'),
      say('ignis', '貴様に、その炎を受けとめる覚悟はあるか。'),
      mood('alto', 'worry'),
      say('alto', '……はい。あの竜を、苦しみから解きたいんです。'),
      bgm('battle2'),
      sfx('horn-3', 0.6),
      shout('ignis', 'よかろう！ 我が炎は千の戦を越えてきた。貴様に耐えられるか！'),
    ],
    after: [
      bgm('menu'),
      bg('story/landscape-lava', 'in'),
      weather('embers'),
      show('alto', 'L', 'normal'),
      show('ignis', 'R'),
      say('ignis', '見事だ……貴様の炎、確かに受け取った。'),
      sfx('magic-holy-1', 0.5),
      fx('flash'),
      narr('そのとき、竜の体から黒い靄がふわりと抜け、霧散した。'),
      show('liese', 'FL', 'glad'),
      say('liese', '霧が……晴れた！？'),
      say('ignis', '戦いのなか、あやつの炎が霧を焼き切ったのだ。……たしかな絆があれば、霧は退けられる。'),
      mood('alto', 'glad'),
      say('alto', 'それなら、ほかの獣たちも救えますね！'),
      say('ignis', '北の平原で、狼の群れが荒れている。霧の晴れた我らの翼なら、すぐに着ける。'),
      say('ignis', '乗れ。この借り、空で返そう。'),
      narr('竜騎士イグナスの翼で、一行は北の平原へと飛び立った。'),
      hide('ignis'),
    ],
    lose: [
      bg('story/landscape-lava', 'in'),
      show('ignis', 'R'),
      say('ignis', '灰となれ！ ……いや、まだだ。立て。炎はまだ、貴様のなかにあるはずだ。'),
    ],
  },

  // ------------------------------------------------------------------ 6 ロウガ
  {
    id: 'c06',
    act: 2,
    rival: 'rouga',
    title: '月下の平原',
    summary: '霧のなかで「声」を聞いたという狼使いロウガ。',
    before: [
      bgm('menu'),
      bg('story/landscape-plain', 'right', { tint: 'rgba(140,150,200,1)' }),
      weather('stars'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('北の平原。夜の風が、遠吠えを運んでくる。'),
      show('rouga', 'R', 'normal', 'rise'),
      whisper('rouga', '……群れが、おまえたちを見ている。'),
      say('liese', 'いつの間に……！ 気配がまったくなかったわ。'),
      say('rouga', '狩りの基本だ。獲物に、気づかれぬこと。'),
      say('alto', 'ぼくたちは獲物じゃない。霧を止めに来たんです。'),
      say('rouga', '……霧、か。', 'normal'),
      say('rouga', '俺は聞いた。霧のなかで、声がした。「目覚めよ」と。'),
      mood('liese', 'normal'),
      say('liese', '声……？ 誰の？'),
      say('rouga', '知らん。だが、群れの半分はその声に従って、北へ去っていった。'),
      say('rouga', '残った群れを預けるに足るか。牙で語ってもらおう。'),
      bgm('battle2'),
      sfx('horn-3', 0.6),
      shout('rouga', '群れの牙から逃げられると思うなよ！'),
    ],
    after: [
      bgm('menu'),
      bg('story/landscape-plain', 'in', { tint: 'rgba(140,150,200,1)' }),
      weather('stars'),
      show('alto', 'L', 'normal'),
      show('rouga', 'R'),
      say('rouga', '……群れを率いる器、お前にはあるようだな。'),
      say('alto', 'さっきの「声」のこと、もう少し教えてもらえませんか？'),
      say('rouga', '低く、古い声だった。「王が目覚める。膝をつけ」と。'),
      say('rouga', 'だが、妙だった。命じる声なのに……ひどく、さびしそうに聞こえた。'),
      mood('alto', 'worry'),
      think('alto', 'さびしそうな声……？ 冥府の王が、ほんとうに黒幕なのかな。'),
      say('rouga', '北の森には蟲の民がいる。やつらも霧にやられているはずだ。'),
      say('rouga', '残った群れは、俺が連れていく。霧の外で待て。終わったら、また走ろう。'),
      hide('rouga'),
    ],
    lose: [
      bg('story/landscape-plain', 'in'),
      show('rouga', 'R'),
      say('rouga', '狩りは終わりだ。……もう一度、群れの前に立てるか？'),
    ],
  },

  // ------------------------------------------------------------------ 7 フローラ
  {
    id: 'c07',
    act: 2,
    rival: 'flora',
    title: '蟲の森',
    summary: '蟲たちの女王を守るドルイド、フローラ。森の奥の古い墓所とは？',
    before: [
      bgm('menu'),
      bg('story/p-black-forest', 'in'),
      weather('fog'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('北の森は、深く、暗い。羽音があちこちから聞こえる。'),
      say('liese', 'ううっ……虫、ちょっと苦手なのよ……。'),
      show('flora', 'R', 'normal', 'fade'),
      say('flora', 'まあ。おびえた騎士さん。森の小さな命たちは、あなたを傷つけたりしないわ。'),
      mood('liese', 'mad'),
      say('liese', 'お、おびえてません！'),
      say('alto', 'あなたが、この森の……？'),
      say('flora', 'フローラ。森のドルイドよ。……ここまで来たなら、見せてもらいましょうか。'),
      say('flora', '森の小さな命たち。その数を、甘く見ないことね。'),
      say('alto', '待ってください、ぼくたちは——'),
      say('flora', '言葉はいらないわ。森は、戦いのなかでしか人を知らないの。'),
      bgm('battle1'),
      sfx('horn-3', 0.6),
      shout('flora', '女王の目覚めを、見せてあげる！'),
    ],
    after: [
      bgm('menu'),
      bg('story/p-black-forest', 'in'),
      weather('motes'),
      show('alto', 'L', 'glad'),
      show('liese', 'FL', 'normal'),
      show('flora', 'R'),
      say('flora', 'あなた、森に愛されているのね。蟲たちが、騒ぐのをやめたわ。'),
      say('liese', '……ほんとうに、おとなしくなった。'),
      say('flora', '霧のことは知っているわ。森の北、古い墓所のあたりから、少しずつ流れ出している。'),
      say('alto', '古い墓所……？'),
      say('flora', '千年前、冥府の王を封じた場所よ。封印は、もう長くはもたないでしょう。'),
      say('liese', 'やっぱり、そこが震源……。'),
      say('flora', '行くなら、気をつけて。あの墓所へ向かう道には、巨人を従える大戦士長がいるわ。'),
      say('flora', '彼の軍勢は、霧に心を縛られている。……どうか、止めてあげて。'),
      hide('flora'),
    ],
    lose: [
      bg('story/p-black-forest', 'in'),
      show('flora', 'R'),
      say('flora', '森の命は、数ではなく絆よ。……もう一度、聞かせて。あなたの絆を。'),
    ],
  },

  // ------------------------------------------------------------------ 8 ガルム
  {
    id: 'c08',
    act: 2,
    rival: 'garm',
    title: '大戦士長の行軍',
    summary: '霧に縛られた巨人の軍勢を率いる、オークの大戦士長ガルム。',
    before: [
      bgm('menu'),
      bg('story/landscape-mountains-03', 'down'),
      weather('ash'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('grom', 'C', 'normal'),
      narr('墓所へ続く荒れ地。黒い旗をかかげた大軍が、地平線を埋めていた。'),
      say('grom', 'グハハ……ずいぶんな数だな。おもしろい！'),
      say('liese', '笑っている場合じゃないわ！ この数、王都まで押し寄せたら……'),
      show('garm', 'R', 'normal', 'drop'),
      fx('quake'),
      shout('garm', '止まれ。これより先は、我が軍勢の行軍路だ。'),
      say('alto', '大戦士長ガルム……ですね。軍をどこへ向けているんですか。'),
      say('garm', '知らぬ。……ただ、北へ進めと、頭のなかで声が鳴りやまぬのだ。'),
      mood('garm', 'normal'),
      say('garm', '我が軍勢は、倒れても立ち上がる。だが、心だけは、とうに折れかけている。'),
      say('garm', 'せめて最後は、戦士として散りたい。……我と戦え、若き召喚士。'),
      mood('alto', 'normal'),
      say('alto', '散らせはしません。ぼくが、あなたの心を折らせない。'),
      bgm('battle3'),
      sfx('horn-3', 0.6),
      shout('garm', '進め！ 巨人の行軍は止まらぬ！ 我が軍勢の力、見せてくれる！'),
    ],
    after: [
      bgm('menu'),
      bg('story/landscape-mountains-03', 'in'),
      weather('motes'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'glad'),
      show('garm', 'R'),
      say('garm', '……見事。お前を、戦士と認めよう。'),
      sfx('magic-holy-1', 0.5),
      fx('flash'),
      narr('そのとき、軍勢を包んでいた黒い霧がすうっと消えた。'),
      say('garm', '頭が……軽い。何年も、霧のなかを歩いていたようだ。'),
      say('liese', 'みんなの目が、澄んでいくわ……！'),
      say('garm', '若き召喚士よ。我らは王都を守る盾となろう。霧の主を叩くなら、これが先陣だ。'),
      say('grom', 'グハハ！ 負けておれんな！ 先に殴りかかるのはオレ様だ！'),
      narr('山脈の戦いは終わった。残る霧は、海と氷の大地に——。'),
      hide('garm'),
    ],
    lose: [
      bg('story/landscape-mountains-03', 'in'),
      show('garm', 'R'),
      say('garm', '我が軍勢は倒れても立ち上がる。……お前の心は、どうだ？'),
    ],
  },
];
