// 第3幕「深淵と氷原」 — ネレア / セツナ / ヴェルド / ジーク
import { bg, bgm, fx, hide, mood, narr, say, show, shout, sfx, title, weather } from './dsl';
import type { Act, Chapter } from './types';

export const ACT3: Act = { no: 3, title: '深淵と氷原', sub: '四つの守護と、王都の盾', bg: 'story/p-storm-sea' };

export const ACT3_CHAPTERS: Chapter[] = [
  // ------------------------------------------------------------------ 9 ネレア
  {
    id: 'c09',
    act: 3,
    rival: 'nerea',
    title: '深淵の神殿',
    summary: '海底の神殿で、海の底を守る巫女王ネレアが待つ。',
    before: [
      bgm('menu'),
      title('第三幕　深淵と氷原', '四つの守護と、王都の盾', 'ACT III'),
      bg('story/p-wild-sea', 'in'),
      weather('rain'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('海は荒れていた。マリナにもらった巻き貝が、かすかに震えている。'),
      sfx('magic-holy-2', 0.4),
      say('alto', '……聞こえる。貝が、「こっちだ」って。'),
      bg('story/p-temple', 'in', { tint: 'rgba(120,200,220,1)' }),
      weather('motes'),
      narr('導かれるまま、一行は不思議な光に包まれ——海の底の神殿にたどり着いた。'),
      show('nerea', 'R', 'normal', 'fade'),
      say('nerea', 'ようこそ、地上の子ら。わたくしは深淵の巫女王ネレア。'),
      say('nerea', '潮の巫女の貝を持つ者……あなたが、アルトですね。'),
      say('alto', '知っているんですか、ぼくのこと？'),
      say('nerea', '海はすべて語ります。霧を止めようとする、小さな召喚士のことを。'),
      say('nerea', 'でも、深淵の力を借りるには、その覚悟を示してもらわなければなりません。'),
      say('liese', '覚悟……戦いで、ということね。'),
      say('nerea', 'ええ。深い海は、浅い心では耐えられませんから。'),
      bgm('battle3'),
      sfx('horn-3', 0.6),
      shout('nerea', '深淵の底で、見せてください。あなたの光を。'),
    ],
    after: [
      bgm('menu'),
      bg('story/p-temple', 'in', { tint: 'rgba(120,200,220,1)' }),
      weather('motes'),
      show('alto', 'L', 'glad'),
      show('nerea', 'R'),
      say('nerea', '見事です。深い海もあなたを受け入れました。'),
      sfx('magic-holy-1', 0.5),
      narr('ネレアは胸もとの真珠を外し、アルトに手渡した。'),
      say('nerea', 'この真珠は、深淵の子らの絆の証。海の民は、あなたに力を貸します。'),
      say('nerea', '霧は、北の氷原でいっそう濃くなっています。氷河の魔導士をたずねなさい。'),
      say('nerea', '彼女なら、霧の流れを読めるはず。'),
      mood('alto', 'normal'),
      say('alto', 'ありがとうございます、ネレアさま。'),
      say('nerea', '気をつけて。……霧の奥にいるのは、王ひとりではない気がするのです。'),
      hide('nerea'),
    ],
    lose: [
      bg('story/p-temple', 'in', { tint: 'rgba(120,200,220,1)' }),
      show('nerea', 'R'),
      say('nerea', '深淵に沈むものは、うつくしい。……ですが、あなたはまだ浮かび上がれるはずです。'),
    ],
  },

  // ------------------------------------------------------------------ 10 セツナ
  {
    id: 'c10',
    act: 3,
    rival: 'setsuna',
    title: '氷河の魔導士',
    summary: '凍てつく氷原で霧の流れを読む魔導士セツナ。',
    before: [
      bgm('menu'),
      bg('story/p-snowfield', 'in'),
      weather('snow'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('氷原。吐く息が、そのまま白い結晶になる。'),
      say('liese', 'さ、寒い……！ 鎧が凍りそう……！'),
      show('setsuna', 'R', 'normal', 'fade'),
      say('setsuna', 'こんなところまで、よく来たわね。人の子にしては、上出来よ。'),
      say('alto', 'セツナさん、ですよね。霧の流れを読めると聞いて、来ました。'),
      say('setsuna', '読めるわ。……だからこそ、あなたたちを試したいの。'),
      say('setsuna', '霧の源は、氷より冷たい場所にある。そこへ行く者は、心まで凍らせてはいけない。'),
      mood('alto', 'normal'),
      say('alto', '凍らせません。ぼくは、あきらめが悪いので。'),
      say('setsuna', '……ふふ。いいわ。その言葉、氷の下まで届くかしら。'),
      bgm('battle3'),
      sfx('horn-3', 0.6),
      shout('setsuna', '氷河の底で、凍りついてみせなさい！'),
    ],
    after: [
      bgm('menu'),
      bg('story/p-snowfield', 'in'),
      weather('snow'),
      show('alto', 'L', 'glad'),
      show('liese', 'FL', 'glad'),
      show('setsuna', 'R'),
      say('setsuna', '……あたたかい戦い方をするのね。氷が少し、溶けてしまったわ。'),
      narr('セツナは杖を振り、空中に光の地図を描いた。'),
      say('setsuna', '霧は、ここ。大陸の北東、古い王国の跡地から流れているわ。'),
      say('setsuna', '「影の王国」。かつて、冥府の王が築いた夜の国よ。'),
      say('liese', '王国の跡地……そこに、冥府の王が眠っているのね。'),
      say('setsuna', 'そう。でも、そこへ行く前に、会うべき人がいるわ。'),
      say('setsuna', '古い森の守り手と、王都の竜騎士団長。彼らの協力なしでは、影の王国には届かない。'),
      hide('setsuna'),
    ],
    lose: [
      bg('story/p-snowfield', 'in'),
      show('setsuna', 'R'),
      say('setsuna', '氷は、割れてもまた張るもの。……もう一度、立ち上がりなさい。'),
    ],
  },

  // ------------------------------------------------------------------ 11 ヴェルド
  {
    id: 'c11',
    act: 3,
    rival: 'verd',
    title: '古竜の守り手',
    summary: '千年を生きる古竜と、森の守り手ヴェルド。',
    before: [
      bgm('menu'),
      bg('story/p-great-tree', 'down'),
      weather('motes'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('古い森。ここの木々は、ひとの千年より長く生きている。'),
      show('verd', 'R', 'normal', 'fade'),
      say('verd', '……人の足音。久しいな。'),
      say('alto', 'あなたが、古竜の守り手のヴェルドさん？'),
      say('verd', 'そうだ。この森の奥に、千年を眠る古き竜がいる。'),
      say('verd', '霧が近づけば、あの子は目を覚ます。……あの子が暴れれば、大陸が割れる。'),
      say('liese', 'そんな力を持った竜が……。'),
      say('verd', '力を貸してほしいと、言いに来たのだろう。だが、私が見極めるのは、力ではない。'),
      say('verd', '「命を預かる覚悟」だ。'),
      mood('alto', 'normal'),
      say('alto', '……分かりました。ぼくの全部で、お答えします。'),
      bgm('battle3'),
      sfx('horn-3', 0.6),
      shout('verd', '来い！ 古の竜の目の前で、その覚悟を示せ！'),
    ],
    after: [
      bgm('menu'),
      bg('story/p-great-tree', 'in'),
      weather('motes'),
      show('alto', 'L', 'glad'),
      show('verd', 'R'),
      say('verd', '……見事だ。あの子が、目を細めている。'),
      sfx('rumble', 0.4),
      fx('quake'),
      narr('森の奥で、巨大な何かがゆっくりと身を起こした。しかし、その気配は穏やかだった。'),
      say('verd', '古の竜は、お前を気に入ったようだ。必要なとき、必ず駆けつけよう。'),
      say('liese', 'ほんとうに……味方になってくれるのね。'),
      say('verd', 'ただし、条件がある。竜の力を借りるなら、王都の騎士団長に会え。'),
      say('verd', 'あの男は、竜と人を結ぶ橋だ。……そして、私の友でもある。'),
      hide('verd'),
    ],
    lose: [
      bg('story/p-great-tree', 'in'),
      show('verd', 'R'),
      say('verd', '命は重い。……焦るな。もう一度、静かに向き合うのだ。'),
    ],
  },

  // ------------------------------------------------------------------ 12 ジーク
  {
    id: 'c12',
    act: 3,
    rival: 'sieg',
    title: '王都の門',
    summary: '王都の門で待つ覇竜騎士団長ジーク。王への謁見をかけた最後の関門。',
    before: [
      bgm('menu'),
      bg('story/landscape-castle', 'in'),
      weather('petals'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'glad'),
      narr('白い城壁が見えてきた。王都——アルカナ最大の都。'),
      say('liese', '帰ってきた……！ みんな、ここが私の故郷よ。'),
      show('sieg', 'R', 'normal', 'drop'),
      shout('sieg', 'リーゼ！ ようやく戻ったか！'),
      mood('liese', 'normal'),
      say('liese', 'だ、団長！ ご報告があります！ 北の霧は、冥府の王の——'),
      say('sieg', '知っている。全て、斥候から聞いた。……そこの少年が、アルトか。'),
      say('alto', 'はい。王にお会いしたいのです。霧を止めるために、騎士団の力を借りたくて。'),
      say('sieg', '王へ会う前に、私の試験を受けてもらう。竜騎士団長として、見極めねばならん。'),
      say('sieg', '覇竜の騎士団は、半端な覚悟の者と並んで飛ばぬ。それが誇りだ。'),
      say('liese', '団長……！'),
      say('sieg', '案ずるな、リーゼ。彼が本物なら、私の剣は届かぬ。'),
      bgm('boss'),
      sfx('horn-3', 0.6),
      shout('sieg', '覇竜の力、その身に刻め！ いざ、勝負！'),
    ],
    after: [
      bgm('victory'),
      bg('story/landscape-castle', 'in'),
      weather('petals'),
      show('alto', 'L', 'glad'),
      show('liese', 'FL', 'glad'),
      show('sieg', 'R'),
      say('sieg', '……見事だ。王も、きっとお喜びになる。'),
      say('sieg', 'アルト殿。覇竜騎士団は、あなたの旗のもとに集おう。'),
      fx('flash'),
      sfx('fanfare-short', 0.7),
      narr('竜騎士たちが一斉に剣を掲げた。城壁の上で、無数のドレイクが咆哮する。'),
      say('liese', 'みんな……！ ほら、アルト、見て！ 騎士団が、あなたに誓いを立てているのよ！'),
      mood('alto', 'worry'),
      say('alto', 'こ、こんなに大勢の人が……ぼくなんかに？'),
      say('sieg', '力は、人を動かす。だが、本当に人を動かすのは、あなたのような「真っすぐな心」だ。'),
      say('sieg', '行こう。影の王国へ。大陸の夜を、終わらせるために。'),
      bgm('menu'),
      hide('sieg'),
    ],
    lose: [
      bg('story/landscape-castle', 'in'),
      show('sieg', 'R'),
      say('sieg', 'まだだ。覇竜の翼は、折れた者を二度と飛ばせない。……立て！'),
    ],
  },
];
