// 第三幕「ひとりの道」 — ネレア / セツナ / ヴェルド
import { bars, bg, bgm, cg, choice, cutin, fx, hide, mood, narr, place, say, show, showCard, shout, sfx, think, title, tone, wait, weather, whisper } from './dsl';
import type { Act, Chapter } from './types';

export const ACT3: Act = { no: 3, title: 'ひとりの道', sub: '雪と、古い傷', bg: 'story/p-snow-hut' };

export const ACT3_CHAPTERS: Chapter[] = [
  // ------------------------------------------------------------------ 7 ネレア
  {
    id: 'n07',
    act: 3,
    rival: 'nerea',
    title: '湖の神殿',
    summary: 'ひとりきりの旅。伝説の一枚を神と崇める教団と、その大巫女。',
    art: 'story/p-temple',
    before: [
      title('第三幕　ひとりの道', '雪と、古い傷', 'ACT III'),
      bgm('transience'),
      bg('story/p-river-mist', 'right'),
      weather('fog'),
      place('鏡の湖', '北の森'),
      show('hero', 'L', 'normal'),
      narr('ひとりで歩く道は、思っていたより長かった。'),
      narr('焚き火をおこすのも、地図を読むのも、気づけば全部リーゼがやってくれていた。'),
      think('hero', '……マント、まだ返してない。'),
      bg('story/p-temple', 'in', { tint: 'rgba(150,200,210,1)' }),
      weather('motes'),
      bgm('shadows'),
      place('湖の神殿', '水底の聖堂'),
      show('cultist', 'FR', 'normal', 'fade'),
      say('cultist', '……巡礼者か。聖なるカードに祈りを捧げに来たのか。'),
      narr('神殿の奥、祭壇の上に、一枚のカードが飾られていた。その前に、何十人もの信徒がひれ伏している。'),
      narr('祭壇の脇には、幼い子どもたちが並んでいた。皆、同じ白い服を着て、同じうつろな目をしていた。'),
      show('nerea', 'R', 'normal', 'rise'),
      sfx('magic-holy-2', 0.5),
      say('nerea', 'ようこそ。十二枚が揃うとき、湖は楽園への門となる。……私たちは、その日を待っているのです。'),
      say('hero', 'あの子たちは？'),
      say('nerea', '親が神殿に捧げた子らです。楽園では、飢えも病もない。……幸せな子たちですよ。'),
      mood('hero', 'mad'),
      say('hero', '……カードを、バトルで譲ってほしい。'),
      say('nerea', '聖なるカードに触れる者には、罰が下ります。それでも挑むのですね。'),
      hide('cultist'),
      cutin('nerea', 'normal', '神の名のもとに'),
      bgm('battle2'),
      shout('nerea', '祈りなさい！'),
    ],
    after: [
      bgm('suspense'),
      bg('story/p-temple', 'in', { tint: 'rgba(130,170,190,1)' }),
      weather('motes'),
      show('hero', 'L', 'normal'),
      show('nerea', 'R', 'normal'),
      say('nerea', '……神よ。なぜ、この者を選ぶのですか。'),
      showCard('ナーガクイーン', '伝説のカード　八枚目'),
      say('nerea', '……ひとつ、教えてあげましょう。この神殿で一番古い巻物には、楽園のことなど書かれていなかった。'),
      say('nerea', '書かれていたのは、「代価」のこと。……私は、それを読んで、燃やしました。'),
      say('hero', '代価……？'),
      say('nerea', '知りたければ、北の氷河の魔導士を訪ねなさい。あの人は、燃やさなかった。'),
      show('cultist', 'FR', 'normal', 'fade'),
      sfx('sword-1', 0.6),
      say('cultist', '聖なるカードを……返せ！ 盗人め！'),
      fx('shake'),
      narr('信徒たちが、一斉に立ち上がった。手には、燭台や、祭壇の石。'),
      say('nerea', '行きなさい。……私にはもう、彼らを止められない。'),
      bgm('battle3'),
      fx('fadeBlack'),
      wait(400),
      hide('cultist'),
      hide('nerea'),
      bg('story/p-river-mist', 'right', { tint: 'rgba(120,140,170,1)' }),
      weather('rain'),
      fx('unfade'),
      narr('どこをどう走ったのか、覚えていない。気がつくと、湖の向こう岸で、膝をついていた。'),
      narr('額から血が流れていた。手の中のカードだけは、離していなかった。'),
      think('hero', '……八枚。'),
    ],
    lose: [
      bg('story/p-temple', 'in', { tint: 'rgba(150,200,210,1)' }),
      show('nerea', 'C'),
      say('nerea', '神は、あなたを拒みました。……それでも、また来るのですね。'),
    ],
  },

  // ------------------------------------------------------------------ 8 セツナ
  {
    id: 'n08',
    act: 3,
    rival: 'setsuna',
    title: '氷河の伝承',
    summary: '伝承を知る魔導士が語る「代価」。そして、雪の中から戻ってきたのは——。',
    art: 'story/p-snow-hut',
    before: [
      bgm('silence'),
      bg('story/p-snowfield', 'right'),
      weather('snow'),
      place('白の氷河', '大陸の北'),
      show('hero', 'L', 'normal'),
      narr('吹雪。指の感覚が、もうない。'),
      narr('氷河のほとりに、小さな小屋がひとつ。煙突から、細い煙が上がっていた。'),
      bg('story/p-snow-hut', 'in'),
      show('setsuna', 'R', 'normal', 'fade'),
      say('setsuna', '……湖の大巫女の使いですか。それとも、ただの迷子？'),
      say('hero', '伝説のカードの「代価」のことを、知りたくて来た。'),
      say('setsuna', '……そう。燃やさなかった者のところへ、来てしまったのですね。'),
      say('setsuna', '伝承を知りたいのなら、まず、私に勝ちなさい。知る覚悟のない者に、教えることはありません。'),
      bgm('battle2'),
      sfx('magic-faeriefire', 0.5),
      shout('setsuna', '凍てつく風よ！'),
    ],
    after: [
      bgm('revelation'),
      bg('story/p-snow-hut', 'in', { tint: 'rgba(170,190,230,1)' }),
      weather('snow'),
      show('hero', 'L', 'normal'),
      show('setsuna', 'R', 'normal'),
      say('setsuna', '……いいでしょう。代価を、教えてあげます。'),
      showCard('スノーゴーレム', '伝説のカード　九枚目'),
      tone('sepia'),
      bars(true),
      cg('story/p-shrine', 'in', '大魔導士の手記'),
      say('setsuna', '「十二枚を揃え、始まりの庭で掲げた者に、永遠を」。……これは伝承の前半です。'),
      say('setsuna', '後半は、こう続きます。'),
      whisper('setsuna', '「その代わり、十二枚を勝ち取りし者の故郷は、その命を、ひとつ残らず庭に捧げる」'),
      cg(null),
      bars(false),
      tone('none'),
      mood('hero', 'worry'),
      say('hero', '……命を、捧げる？'),
      say('setsuna', '霊薬など、どこにも書かれていない。あるのは「永遠」と、その代わりに消える町の名前だけ。'),
      say('setsuna', '掲げる者と、勝ち取る者は、別でもいい。……だからこそ、恐ろしい伝承なのです。'),
      think('hero', '……勝ち取りし者の、故郷。'),
      think('hero', '……先生は、霊薬が湧くと言った。きっと、先生も知らないんだ。'),
      say('hero', '……それでも、先生に届けます。届けて、伝えます。掲げちゃいけないって。'),
      say('setsuna', '……そう。あなたは、まだ師を信じているのですね。'),

      bgm('love'),
      narr('——小屋の扉が、乱暴に叩かれた。'),
      show('liese', 'FL', 'hurt', 'fade'),
      narr('雪まみれのリーゼが、そこに立っていた。'),
      say('hero', '……リーゼ。'),
      say('liese', '……やっと、見つけた。'),
      say('liese', '弟ね。……死んだの。三週間前。'),
      say('liese', '薬、間に合わなかった。あんたを裏切って稼いだお金、一枚も使えなかった。'),
      narr('リーゼは、笑おうとして、失敗した。'),
      say('liese', '馬鹿みたいでしょ。……もう、帰る家も、送る手紙もないの。'),
      say('liese', '依頼人の名前、教える。カーミラ。王都の、夜会の女主人。……それから、残りの前払いも全部返す。'),
      say('liese', 'だから……もう一回、護衛させて。今度は、お金いらない。'),
      choice('リーゼに、なんと言う？', [
        { label: '「……マント、返さなきゃと思ってた」', then: [mood('hero', 'normal'), say('hero', '……マント、ずっと返さなきゃと思ってた。'), mood('liese', 'glad'), say('liese', '……なにそれ。ほんと、甘い。'), narr('リーゼは、泣きながら笑った。')] },
        { label: '「次は、ちゃんと話して」', then: [mood('hero', 'worry'), say('hero', '……次からは、ちゃんと話して。どんなことでも。'), mood('liese', 'normal'), say('liese', '……うん。約束する。')] },
      ]),
      say('setsuna', '……行くのですね、ふたりで。'),
      say('setsuna', 'この先の森に、あなたの師を知る者がいます。……会っておきなさい。'),
    ],
    lose: [
      bg('story/p-snow-hut', 'in'),
      weather('snow'),
      show('setsuna', 'C'),
      say('setsuna', '知らないほうが、幸せなこともあるのです。……それでも、また来ますか。'),
    ],
  },

  // ------------------------------------------------------------------ 9 ヴェルド
  {
    id: 'n09',
    act: 3,
    rival: 'verd',
    title: '古竜の森',
    summary: '四十年前、オルデンと共に旅をしたエルフ。その目に浮かぶのは、懐かしさではなかった。',
    art: 'story/p-fire-sky',
    before: [
      bgm('legends'),
      bg('story/p-elf-wood', 'in'),
      weather('motes'),
      place('古竜の森', '東の大森林'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('巨木の根が、川のようにうねっていた。'),
      bg('story/p-great-tree', 'in'),
      show('verd', 'R', 'normal', 'fade'),
      say('verd', '……あの男の弟子か。'),
      say('verd', 'その顔、昔のあいつにそっくりだ。勝ちを疑わない、まっすぐな目。'),
      say('hero', '先生を、知ってるんですか。'),
      say('verd', '四十年前、ふたりで十二枚を探して旅をした。……あいつが、私を竜の巣に置き去りにするまではな。'),
      tone('sepia'),
      cg('story/p-burning', 'in', '四十年前'),
      sfx('flame-big', 0.4),
      narr('炎の中で、若いオルデンは振り返らなかった。仲間の持っていた三枚のカードを抱えて、走り去った。'),
      whisper('verd', '「すまん。だが、おまえより、こっちのほうが大事なんだ」……あいつは、そう言った。'),
      cg(null),
      tone('none'),
      mood('hero', 'mad'),
      say('hero', '……そんなの、嘘だ。先生は、親のない自分を拾ってくれた人だ。'),
      say('verd', '拾った、か。……なぜ拾ったのか、考えたことはあるか。'),
      say('hero', '……！'),
      mood('liese', 'mad'),
      say('liese', 'やめて。{name}は、何も知らずに……'),
      say('verd', '知らずに、ここまで勝ってきた。それが一番、恐ろしいのだ。'),
      say('verd', '最後の一枚は渡せない。あの男の手に渡るくらいなら、森ごと燃やす。……止めたければ、勝ってみろ。'),
      bgm('battle3'),
      cutin('verd', 'normal', '森の吐息に抗えるか'),
      shout('verd', '来い、オルデンの弟子！'),
    ],
    after: [
      bgm('sad'),
      bg('story/p-great-tree', 'in', { tint: 'rgba(200,180,140,1)' }),
      weather('motes'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('verd', 'R', 'normal'),
      say('verd', '……行くのか。なら、覚悟して行け。'),
      showCard('エルダーワイアーム', '伝説のカード　十枚目'),
      say('verd', 'ひとつだけ、覚えておけ。オルデンの故郷は、四十年前の流行り病で、もう無い。'),
      mood('hero', 'worry'),
      say('verd', 'あいつがおまえを拾ったのは、どこだ？ ……おまえの故郷は、どこだ？'),
      wait(700),
      bgm('revelation'),
      fx('zoomPunch'),
      tone('cold'),
      think('hero', '「十二枚を勝ち取りし者の故郷は、その命を、ひとつ残らず庭に捧げる」'),
      think('hero', '勝ち取るのは——自分。'),
      think('hero', '故郷は——リーフェル。'),
      say('liese', '……{name}？ 顔、真っ青だよ。'),
      say('hero', '……違う。先生は、そんな人じゃない。'),
      say('hero', '確かめる。……王都へ行こう、リーゼ。カーミラに、直接聞く。'),
      tone('none'),
      title('第三幕　完', '十枚の伝説', 'ACT III'),
    ],
    lose: [
      bg('story/p-great-tree', 'in'),
      show('verd', 'C'),
      say('verd', '森へ帰りな。庭へは、行くんじゃない。'),
    ],
  },
];

