// 第四幕「始まりの庭」 — カーミラ / モルガナ / オルデン
import { bars, bg, bgm, cg, choice, cutin, fx, hide, mood, move, narr, place, say, show, showCard, shout, sfx, title, tone, wait, weather, whisper } from './dsl';
import type { Act, Chapter } from './types';

export const ACT4: Act = { no: 4, title: '始まりの庭', sub: '永遠の代価', bg: 'story/p-shrine' };

export const ACT4_CHAPTERS: Chapter[] = [
  // ------------------------------------------------------------------ 10 カーミラ
  {
    id: 'n10',
    act: 4,
    rival: 'carmilla',
    title: '夜会の館',
    summary: 'リーゼの依頼人、カーミラ。仮面の夜会で明かされる、本当の雇い主の名。',
    art: 'story/p-bride',
    before: [
      title('第四幕　始まりの庭', '永遠の代価', 'ACT IV'),
      bgm('shadows'),
      bg('story/landscape-castle', 'in', { tint: 'rgba(120,110,170,1)' }),
      weather('none'),
      place('王都', '夜'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('王都の夜は、明るすぎた。'),
      narr('丘の上の館では、毎晩のように仮面の夜会が開かれているという。'),
      bg('story/p-hall', 'in', { tint: 'rgba(170,120,150,1)' }),
      weather('motes'),
      bgm('love'),
      place('カーミラの館', '仮面の夜会'),
      show('agent', 'FR', 'normal', 'fade'),
      say('agent', 'お待ちしておりました。奥様が、お会いになります。'),
      show('carmilla', 'R', 'normal', 'fade'),
      say('carmilla', 'ようこそ、坊や。……あら、可愛い番犬も一緒なのね。'),
      say('carmilla', 'リーゼ、あなたの報告は丁寧で好きだったわ。弟さんのこと、お気の毒に。'),
      mood('liese', 'mad'),
      say('liese', '……っ。'),
      say('hero', '聞きたいことがある。あなたに依頼したのは、誰だ。'),
      say('carmilla', 'うふふ。夜会では、質問はバトルのあとと決まっているの。'),
      say('carmilla', '私に勝ったら、何でも教えてあげる。十一枚目のカードも、一緒にね。'),
      hide('agent'),
      bgm('battle3'),
      cutin('carmilla', 'normal', '最後まで、踊っていられるかしら'),
      shout('carmilla', 'さあ、踊りましょう！'),
    ],
    after: [
      bgm('revelation'),
      bg('story/p-hall', 'in', { tint: 'rgba(150,110,140,1)' }),
      weather('motes'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('carmilla', 'R', 'normal'),
      say('carmilla', '……ふふ、いいわ。約束ですもの。'),
      showCard('ヴァンパイア', '伝説のカード　十一枚目'),
      say('carmilla', '私の雇い主はね——'),
      wait(600),
      fx('zoomPunch'),
      say('carmilla', 'オルデン様よ。あなたの、だいじな先生。'),
      tone('cold'),
      mood('hero', 'worry'),
      say('hero', '……嘘だ。'),
      say('carmilla', '四十年前、あの方は十二枚のうち三枚まで集めた。でも、どうしても残りが勝てなかった。'),
      say('carmilla', '手元に残したのは、赤い竜の一枚だけ。あとの二枚は、わざと手放したの。……あなたが勝ち取りに行けるようにね。'),
      say('carmilla', 'それに、伝承の代価——「勝ち取りし者の故郷」。あの方の故郷は、もう無いでしょう？'),
      say('carmilla', 'だから、新しく用意したのよ。故郷を持つ子を拾って、町ひとつぶんの思い出をあげて、カードを教えて。'),
      say('carmilla', 'あなたが勝つたびに、あの方は一歩ずつ若返る準備をしていたわ。'),
      sfx('magic-dark', 0.5),
      mood('liese', 'mad'),
      say('liese', 'ふざけないで！ {name}は……{name}の十年は、そんなもののために……！'),
      say('carmilla', 'あら、怒るのね。あなたも、お金のために同じことをしたのに。'),
      mood('liese', 'hurt'),
      say('carmilla', 'あの方はもう、始まりの庭にいらっしゃるわ。最後の一枚は、門番の子が持っている。'),
      say('carmilla', '行きなさい。……あなたが行かなくても、あの方は困らないけれど。'),
      hide('carmilla'),
      tone('none'),
      bgm('sad'),
      narr('館を出ると、夜明け前の空が、灰色に濁っていた。'),
      say('liese', '……{name}。'),
      say('hero', '……リーフェルに、帰らなきゃ。みんなに、逃げろって。'),
      say('liese', '間に合わない。ここから三週間はかかる。'),
      say('liese', '庭なら、ここから二日。……止めるなら、庭しかない。'),
      choice('どうする？', [
        { label: '「庭へ行く。先生を止める」', then: [mood('hero', 'mad'), say('hero', '……庭へ行く。先生を、止める。'), say('liese', 'うん。最後まで、一緒に行く。')] },
        { label: '「……全部、自分のせいだ」', then: [mood('hero', 'worry'), say('hero', '……全部、自分のせいだ。勝ちたくて、勝ってきた。'), say('liese', '違う。あんたは、信じてただけ。……だから、止めに行こう。')] },
      ]),
    ],
    lose: [
      bg('story/p-hall', 'in', { tint: 'rgba(170,120,150,1)' }),
      show('carmilla', 'C'),
      say('carmilla', '踊り疲れたかしら。……夜は長いわ。もう一曲、いかが？'),
    ],
  },

  // ------------------------------------------------------------------ 11 モルガナ
  {
    id: 'n11',
    act: 4,
    rival: 'morgana',
    title: '庭の門番',
    summary: 'オルデンの、かつての弟子。真実を知って逃げた彼女は、門の前で待っていた。',
    art: 'story/p-hooded',
    before: [
      bgm('suspense'),
      bg('story/p-lone-tower', 'up'),
      weather('fog'),
      place('始まりの庭', '外門'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('霧の向こうに、白い塔と、崩れかけた門が見えた。'),
      narr('門の前に、黒衣の女がひとり、杖をついて立っていた。'),
      show('morgana', 'R', 'normal', 'fade'),
      say('morgana', '……来たのね。私の、次の子。'),
      say('hero', '……次の？'),
      say('morgana', '二十年前、私もあの人に拾われた。小さな港町で。……あなたと同じように、十二枚を集めて回った。'),
      say('morgana', '九枚目で、伝承の後半を知った。怖くなって、逃げたの。……カードを全部、海に捨てて。'),
      tone('sepia'),
      cg('story/p-bride', 'in', '二十年前'),
      narr('翌年、彼女の故郷の港町は、流行り病で半分が死んだ。'),
      whisper('morgana', '……あの人が、薬を止めたのよ。私への、罰として。'),
      cg(null),
      tone('none'),
      say('morgana', 'だから、ここで待っていた。あの人の次の子を、止めるために。'),
      say('morgana', '最後の一枚は、私が持っている。……あなたが負ければ、十二枚は揃わない。'),
      mood('hero', 'worry'),
      say('hero', '……でも、揃わなくても、先生はまた次の子を拾う。'),
      say('morgana', '……ええ。きっとね。'),
      say('hero', 'だから、行く。先生に会って、終わらせる。'),
      say('morgana', '……そう。なら、ここから先へは、行かせない。あなたのために。'),
      bgm('battle3'),
      cutin('morgana', 'normal', 'これ以上、誰も壊させない'),
      shout('morgana', '眠りなさい、私の後輩！'),
    ],
    after: [
      bgm('elegy'),
      bg('story/p-lone-tower', 'in', { tint: 'rgba(180,170,150,1)' }),
      weather('fog'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('morgana', 'R', 'normal'),
      say('morgana', '……もう、止められないのね。'),
      showCard('リッチロード', '伝説のカード　十二枚目'),
      sfx('magic-holy-2', 0.6),
      fx('flash'),
      narr('十二枚目を受け取った瞬間、かばんの中のカードが、いっせいに震えた。'),
      say('morgana', '揃ったわね。……門は、もう開いている。'),
      say('morgana', 'あなたが勝ったカードは、庭に呼ばれる。持ち主が誰であろうと。'),
      say('morgana', 'いい？ あの人に、掲げさせては駄目。……勝つだけでは、止められないかもしれないけれど。'),
      hide('morgana'),
      say('liese', '……{name}。'),
      say('liese', 'なにがあっても、私、あんたの後ろにいるから。'),
      mood('hero', 'normal'),
      say('hero', '……前に出ないでよ。護衛なのは知ってるけど。'),
      say('liese', 'ふふ。それは、約束できない。', 'glad'),
    ],
    lose: [
      bg('story/p-lone-tower', 'in'),
      weather('fog'),
      show('morgana', 'C'),
      say('morgana', '帰りなさい。まだ、間に合うかもしれない。……本当に、そう思う？'),
    ],
  },

  // ------------------------------------------------------------------ 12 オルデン
  {
    id: 'n12',
    act: 4,
    rival: 'olden',
    title: '始まりの庭',
    summary: '十二枚が揃った。庭の中央で、師が待っている。',
    art: 'story/p-shrine',
    before: [
      bgm('silence'),
      bars(true),
      bg('story/p-shrine', 'up', { tint: 'rgba(200,190,170,1)' }),
      weather('motes'),
      place('始まりの庭', '中央の祭壇'),
      narr('崩れた柱。苔むした石畳。中央の祭壇だけが、新しい花で飾られていた。'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('olden', 'R', 'normal', 'fade'),
      bars(false),
      say('olden', '来たか、{name}。……よく、ここまで勝ち続けてくれた。'),
      say('olden', '咳は、もう出んのじゃよ。おまえが勝つたび、少しずつ楽になった。', 'teach'),
      mood('hero', 'mad'),
      say('hero', '……全部、知ってたんですか。代価のことも。'),
      say('olden', '知っておったとも。わしが、伝承の後半を書き写させたのじゃから。'),
      say('hero', 'リーフェルのみんなも？ ベルタさんも？ ……あの町で、自分を育てたのも？'),
      bgm('revelation'),
      mood('olden', 'mad'),
      say('olden', '育てた？ ……ああ、そうじゃな。十年かけて、丁寧に。'),
      say('olden', '伝承の「故郷」とは、勝ち取りし者が心から帰りたいと願う場所のことじゃ。'),
      say('olden', 'だから、あの町を好きにさせた。祭りも、パンの匂いも、全部な。……おまえは、見事にあの町を愛してくれた。'),
      sfx('magic-dark-big', 0.6),
      fx('quake'),
      tone('cold'),
      say('liese', 'この……！'),
      say('olden', '剣を下ろせ、娘。おまえの弟の薬代を払っていたのは、カーミラ。カーミラに金を払っていたのは、わしじゃ。'),
      mood('liese', 'hurt'),
      say('olden', 'まあよい。最後に、ひとつ機会をやろう。バトルじゃ、{name}。わしに勝てば、儀式を考え直してもよい。'),
      choice('師に、なんと言う？', [
        { label: '「……勝って、止める」', then: [mood('hero', 'mad'), say('hero', '……勝って、止める。先生に教わったやり方で。'), say('olden', 'ほっほ。それでこそ、わしの弟子じゃ。', 'teach')] },
        { label: '「……どうして、自分だったんですか」', then: [mood('hero', 'worry'), say('hero', '……どうして、自分だったんですか。'), say('olden', '才能があった。それに……泣かない子じゃった。都合がよかったのじゃよ。'), mood('hero', 'mad'), say('hero', '……っ！')] },
      ]),
      tone('none'),
      bgm('boss'),
      cutin('olden', 'mad', '四十年分の、最後の一局じゃ'),
      sfx('horn-3', 0.8),
      shout('olden', '来い、{name}！'),
    ],
    after: [
      bgm('suspense'),
      bg('story/p-shrine', 'in', { tint: 'rgba(180,170,160,1)' }),
      weather('motes'),
      show('hero', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('olden', 'R', 'normal'),
      say('olden', '……強くなったな。本当に。', 'teach'),
      say('hero', '……約束です。儀式は、やめてください。'),
      say('olden', '考え直す、と言っただけじゃよ。……考え直した。やはり、やる。'),
      bgm('revelation'),
      sfx('magic-holy-1', 0.7),
      fx('flash'),
      narr('かばんが裂けた。十二枚のカードが宙に舞い、祭壇の上に、円を描いて並んだ。'),
      say('olden', '勝ち取ったのは、おまえじゃ。わしではない。……だから、勝ち負けは関係ないのじゃよ。'),
      narr('老人は、両手を高く掲げた。'),
      fx('fadeWhite'),
      wait(500),
      fx('unfade'),
      mood('olden', 'young'),
      sfx('magic-dark-big', 0.7),
      fx('quake'),
      narr('白い髭が、ほどけるように消えた。皺が、骨が、若い男の形に組み替わっていく。'),
      say('olden', '……ああ。息が、軽い。'),
      mood('hero', 'mad'),
      shout('hero', 'やめろおおっ！'),
      narr('飛びかかろうとした、その瞬間——'),
      say('olden', '邪魔じゃ。'),
      sfx('magicmissile', 0.8),
      fx('flashRed'),
      fx('shake'),
      narr('黒い光の槍が、まっすぐ胸に向かってきた。'),
      narr('目の前に、赤いマントが割り込んだ。'),
      tone('blood'),
      bgm('stop'),
      sfx('human-hit-1', 0.7),
      fx('pulse'),
      mood('liese', 'hurt'),
      move('liese', 'C'),
      narr('リーゼの背中から、光の穂先が突き抜けていた。'),
      wait(800),
      fx('pulse'),
      say('liese', '……ほら。前に、出ちゃった。'),
      say('hero', 'リーゼ、リーゼ！'),
      bgm('sad'),
      mood('hero', 'worry'),
      narr('崩れ落ちる体を、抱きとめた。温かいものが、指の間からあふれて止まらない。'),
      say('liese', '……ごめんね。最初、嘘ついて。'),
      say('liese', '弟がね……あんたに、ちょっと似てた。……甘くて、すぐ人を信じるとこ。'),
      fx('pulse'),
      whisper('liese', '……{name}。あんたとの旅……楽しかった……'),
      whisper('liese', '……マント……返さなくて……いいから……'),
      wait(1200),
      fx('pulse'),
      narr('リーゼは、もう、何も言わなかった。'),
      wait(800),
      hide('liese'),
      say('olden', '……惜しい娘じゃった。まあ、よい。永遠の前では、些事よ。'),
      say('olden', '礼を言うぞ、{name}。おまえは、わしの最高の弟子じゃった。'),
      sfx('magic-holy-2', 0.6),
      fx('fadeWhite'),
      hide('olden'),
      wait(600),
      fx('unfade'),
      narr('光が消えたとき、祭壇には誰もいなかった。十二枚のカードも、なかった。'),
      tone('none'),

      // ---------------------------------------------------------------- homecoming
      fx('fadeBlackSlow'),
      bgm('transience'),
      bg('story/landscape-hills-01', 'left', { tint: 'rgba(150,150,150,1)' }),
      weather('ash'),
      tone('mono'),
      fx('unfade'),
      place('三週間後', 'リーフェルへの道'),
      show('hero', 'L', 'normal'),
      narr('どうやって帰ったのか、ほとんど覚えていない。'),
      narr('肩には、赤いマント。'),
      narr('麦畑は、刈られないまま立ち枯れていた。'),
      bgm('silence'),
      bg('story/p-sunset-town', 'still', { tint: 'rgba(130,130,140,1)' }),
      place('リーフェルの町', ''),
      narr('町は、静まり返っていた。'),
      narr('広場には、夏至祭の飾りが、色の抜けたまま揺れていた。'),
      narr('鳥の声も、犬の声も、子どもの声もしない。'),
      bars(true),
      cg('story/p-farmer', 'still', 'パン屋'),
      narr('パン屋の窓から、竈の前に立つ人影が見えた。'),
      narr('ベルタは、パンをこねる手のまま、灰色の石になっていた。'),
      narr('竈の中のパンも、灰色だった。'),
      cg(null),
      bars(false),
      mood('hero', 'worry'),
      say('hero', '……ただいま。'),
      narr('返事は、なかった。'),
      wait(1500),
      fx('fadeBlackSlow'),
      tone('none'),
      bgm('elegy'),
      title('第一部　完', '十二枚の伝説', 'END OF PART ONE'),
    ],
    lose: [
      bg('story/p-shrine', 'in'),
      show('olden', 'C'),
      say('olden', 'まだまだじゃな。……さあ、立て。わしが教えた通りに。', 'teach'),
    ],
  },
];

