// 第4幕「影の王国」 — リリス / カーミラ / モルガナ / ネクロス
import { bg, bgm, choice, fx, hide, mood, narr, say, show, shout, sfx, title, wait, weather, whisper } from './dsl';
import type { Act, Chapter, Beat } from './types';

export const ACT4: Act = { no: 4, title: '影の王国', sub: '夜の底、冥府の王', bg: 'story/p-graves' };

const lilithIllusion: Beat[] = [
  choice('偽物のリーゼが、手を差しのべてくる……', [
    {
      label: '「きみは、リーゼじゃない」',
      then: [
        mood('alto', 'normal'),
        say('alto', 'きみは、リーゼじゃない。リーゼなら、ぼくが泣き言を言ったら、怒るはずだ。'),
        mood('liese', 'mad'),
        say('liese', 'ふふ……そうね。そう言うと思ったわ。'),
        sfx('magic-dark', 0.5),
      ],
    },
    {
      label: '「……ごめん、でも、行かなきゃ」',
      then: [
        mood('alto', 'worry'),
        say('alto', 'ごめん。でも、ぼくは行かなきゃいけないんだ。本物のリーゼと、約束したから。'),
        mood('liese', 'hurt'),
        say('liese', '……ふうん。迷いながらも、振りきるのね。'),
        sfx('magic-dark', 0.5),
      ],
    },
  ]),
];

export const ACT4_CHAPTERS: Chapter[] = [
  // ------------------------------------------------------------------ 13 リリス
  {
    id: 'c13',
    act: 4,
    rival: 'lilith',
    title: '夢魔の回廊',
    summary: '影の王国の入口、夢と現の境でリリスが待ち受ける。',
    before: [
      bgm('menu'),
      title('第四幕　影の王国', '夜の底、冥府の王', 'ACT IV'),
      bg('story/swamp-02', 'in', { tint: 'rgba(130,100,170,1)' }),
      weather('fog'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('sieg', 'C', 'normal'),
      narr('影の王国。昼も夜もない黒い空の下、足もとには紫の霧がうずまいていた。'),
      say('sieg', '全軍、ここで待機せよ。……この先は、少数で進むほうがよい。'),
      say('liese', '空気が重いわ。まるで、夢のなかを歩いているみたい。'),
      fx('fadeBlack'),
      wait(500),
      hide('sieg'),
      hide('liese'),
      bg('story/p-fog', 'in', { tint: 'rgba(160,110,200,1)' }),
      fx('unfade'),
      say('alto', 'あれ？ みんな……？ リーゼ！ 団長さん！'),
      show('liese', 'FL', 'normal', 'fade'),
      say('liese', 'アルト……こっちよ。もう、戦いなんてやめましょう？'),
      mood('alto', 'worry'),
      say('alto', 'リーゼ……？'),
      say('liese', '私と一緒に、帰りましょう？ 村に戻って、またティムたちと遊ぶの。', 'glad'),
      ...lilithIllusion,
      fx('flash'),
      hide('liese'),
      show('lilith', 'R', 'normal', 'drop'),
      say('lilith', 'ふふ……いい夢を見せてあげたつもりだったのに。つれない子。'),
      say('alto', 'あなたが、夢魔の魔女……リリス！'),
      say('lilith', '覚えていて。この回廊を抜けたければ、私を倒しなさい。'),
      say('lilith', '二度と覚めない夢のなかで、あなたの心が折れないか、見ていてあげる。'),
      bgm('battle3'),
      sfx('horn-3', 0.6),
      shout('lilith', 'おやすみなさい、永遠に……！'),
    ],
    after: [
      bgm('menu'),
      bg('story/p-fog', 'in', { tint: 'rgba(160,110,200,1)' }),
      show('alto', 'L', 'normal'),
      show('lilith', 'R', 'normal'),
      say('lilith', 'あら……悪夢から目覚めるなんて、面白い人。'),
      sfx('magic-holy-1', 0.5),
      fx('flash'),
      narr('夢の霧が晴れ、リーゼとジークの姿が戻ってきた。'),
      show('liese', 'FL', 'glad'),
      say('liese', 'アルト！ よかった、無事だったのね！ 急に姿が見えなくなって……'),
      say('alto', '大丈夫。ちょっと、長い夢を見てただけ。'),
      say('lilith', '先へ行きなさい。夜会の主が、お待ちかねよ。'),
      say('lilith', '私は夢を操るだけ。でも、あの方たちは……本気で、あなたたちの命を欲しがっているわ。'),
      hide('lilith'),
    ],
    lose: [
      bg('story/p-fog', 'in', { tint: 'rgba(160,110,200,1)' }),
      show('lilith', 'R'),
      say('lilith', 'おやすみなさい、永遠に……。ふふ、また目覚めたら、遊んであげる。'),
    ],
  },

  // ------------------------------------------------------------------ 14 カーミラ
  {
    id: 'c14',
    act: 4,
    rival: 'carmilla',
    title: '夜会の広間',
    summary: '紅い月の下で開かれる夜会。女主人カーミラが手招きする。',
    before: [
      bgm('menu'),
      bg('story/landscape-castle', 'in', { tint: 'rgba(120,60,90,1)' }),
      weather('stars'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('黒い城の大広間。紅い月が、シャンデリアのかわりに輝いていた。'),
      show('carmilla', 'R', 'normal', 'fade'),
      say('carmilla', 'ようこそ、小さなお客様がた。今宵は、わたくしの夜会へ。'),
      say('liese', '客……？ ここは敵地です、こんな——'),
      say('carmilla', 'お客様は、お客様よ。お食事の前に、ひとつ遊びましょう。'),
      say('carmilla', '勝てたなら、あなたたちの望みを聞いてあげるわ。'),
      say('alto', '望み……ぼくの望みは、霧を止めることです。冥府の王に会わせてください。'),
      say('carmilla', 'ふふ。あの方に会うには、まだ早いわ。', 'normal'),
      say('carmilla', '血が踊るような勝負をしましょう？ 夜は、長いのだから。'),
      bgm('battle3'),
      sfx('horn-3', 0.6),
      shout('carmilla', '夜会のはじまりよ。踊ってちょうだい！'),
    ],
    after: [
      bgm('menu'),
      bg('story/landscape-castle', 'in', { tint: 'rgba(120,60,90,1)' }),
      weather('stars'),
      show('alto', 'L', 'glad'),
      show('liese', 'FL', 'normal'),
      show('carmilla', 'R'),
      say('carmilla', '……あら。久しぶりに、胸が熱くなったわ。'),
      say('carmilla', '約束どおり、教えてあげる。冥府の王は、もう千年も前から、玉座で眠り続けているの。'),
      say('liese', '眠って……いる？'),
      say('carmilla', 'ええ。この霧は、あの方の意思ではないわ。誰かが、王の名を借りて、大地を覆っているのよ。'),
      mood('alto', 'worry'),
      say('alto', '王じゃない……？ それなら、いったい誰が……'),
      say('carmilla', 'それを知りたければ、墓所の主に会いなさい。亡国の死霊術師——あの人なら、全部知っているわ。'),
      say('carmilla', 'でも気をつけて。彼女は、あなたたちを、決して通さないでしょうから。'),
      hide('carmilla'),
    ],
    lose: [
      bg('story/landscape-castle', 'in', { tint: 'rgba(120,60,90,1)' }),
      show('carmilla', 'R'),
      say('carmilla', 'ふふ、まだ踊り足りないわ。……もう一曲、いかが？'),
    ],
  },

  // ------------------------------------------------------------------ 15 モルガナ
  {
    id: 'c15',
    act: 4,
    rival: 'morgana',
    title: '亡国の墓所',
    summary: '千年前の王国の墓所を守る死霊術師モルガナ。',
    before: [
      bgm('menu'),
      bg('story/p-graves', 'in'),
      weather('ash'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('千年前の王国の墓所。石棺が、どこまでも続いている。'),
      show('morgana', 'R', 'normal', 'rise'),
      say('morgana', 'これ以上、進ませない。……あの方を、起こしてはいけない。'),
      say('alto', 'あなたが、モルガナさん？ ぼくたちは、冥府の王を起こしに来たんじゃ——'),
      mood('morgana', 'normal'),
      say('morgana', '起こさない？ ならば何をしに？ この霧を、ここまで歩いてきて……！'),
      say('liese', '私たちは、霧を止めに来たんです。誰かが王の名を借りて、大地に霧を流していると聞きました。'),
      mood('morgana', 'normal'),
      say('morgana', '……聞いたのね、カーミラから。ええ、そのとおり。'),
      say('morgana', 'でも、それを知ったあなたたちを、あの方は許さない。……だから、私が止める。'),
      say('alto', 'あの方……？ 誰のことですか！？'),
      say('morgana', '知らないほうが、きっと幸せよ。——いくわよ、若き召喚士。'),
      bgm('boss'),
      sfx('horn-3', 0.6),
      shout('morgana', '亡国の死者たちよ、目を覚ませ！'),
    ],
    after: [
      bgm('menu'),
      bg('story/p-graves', 'in'),
      weather('motes'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'hurt'),
      show('morgana', 'R'),
      say('morgana', '……そう。やはり、あなたは本物ね。'),
      sfx('magic-holy-1', 0.5),
      narr('モルガナの周りから、黒い鎖が音を立てて砕け散った。'),
      say('morgana', '解けた……ずっと、首を締めつけていた鎖が……。'),
      say('alto', '縛られていたんですか、あなたも。'),
      say('morgana', '千年前の約束で、ね。この墓所を守る代わりに、私は——「あの方」に命を預けたの。'),
      say('morgana', '「影の女王」。霧を放つ、本当の黒幕。……冥府の王を眠らせたまま、その力だけを奪っている女よ。'),
      mood('liese', 'mad'),
      say('liese', '影の……女王……！'),
      say('morgana', '王の間へ行きなさい。そこに、すべての答えがある。'),
      say('morgana', '冥府の王を起こさずに済む方法は、ただひとつ。——彼と、戦うこと。'),
      hide('morgana'),
    ],
    lose: [
      bg('story/p-graves', 'in'),
      show('morgana', 'R'),
      say('morgana', '死者は、数えきれないほどいるの。……あなたの勇気は、あといくつ残っている？'),
    ],
  },

  // ------------------------------------------------------------------ 16 ネクロス
  {
    id: 'c16',
    act: 4,
    rival: 'necros',
    title: '冥府の王',
    summary: '玉座に眠る千年の王。大陸の夜に、決着をつける。',
    before: [
      bgm('menu'),
      bg('story/bones', 'in', { tint: 'rgba(60,70,120,1)' }),
      weather('fog'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('王の間。千年の闇が、静かに降り積もっている。'),
      narr('玉座の上、冷たい王冠が、鈍く光っていた。'),
      say('liese', '……誰も、いない？'),
      sfx('rumble', 0.5),
      fx('quake'),
      weather('storm'),
      show('necros', 'C', 'normal', 'rise'),
      shout('necros', '千年の眠りを妨げし者よ……！'),
      say('necros', 'その魂、我が軍勢に加えてくれよう。'),
      say('alto', '冥府の王ネクロス……！ あなたと、戦います。'),
      say('necros', '戦う、だと？ 虫けらのような小さき者が、我と？'),
      choice('王に、どう答える？', [
        {
          label: '「ぼくひとりじゃない」',
          then: [
            mood('alto', 'glad'),
            say('alto', 'ぼくひとりじゃない！ ここまで一緒に来てくれたみんなの絆が、ぼくの力だ！'),
            mood('liese', 'glad'),
            say('liese', 'そうよ。私たちが、ついてる！'),
          ],
        },
        {
          label: '「あなたを、止めたい」',
          then: [
            mood('alto', 'worry'),
            say('alto', 'あなたを、倒したいんじゃない。止めたいんです。……その苦しみから。'),
            mood('necros', 'normal'),
            say('necros', '……苦しみ、だと？ ……戯れ言を。'),
          ],
        },
      ]),
      mood('alto', 'normal'),
      say('necros', '来るがよい。我が千年の闇を、その身で知れ。'),
      bgm('boss'),
      sfx('horn-3', 0.7),
      shout('necros', '魂は、すべて我がもの！ かかってこい、召喚士！'),
    ],
    after: [
      bgm('menu'),
      bg('story/bones', 'in', { tint: 'rgba(60,70,120,1)' }),
      weather('none'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('necros', 'R', 'normal'),
      say('necros', 'バカな……この我が敗れるだと……！'),
      sfx('lich-die', 0.5),
      fx('flash'),
      narr('王の体から、黒い霧が噴き出し、すうっと天井へ昇っていった。'),
      say('necros', '……ああ。やっと……やっと、眠れる……。'),
      mood('alto', 'worry'),
      say('alto', '待って！ あなたは、無理やり起こされていたんですね？'),
      say('necros', '……そうだ。我は、ただの器。千年前の王の、抜け殻にすぎぬ。'),
      say('necros', '「あの女」は、我を目覚めさせ、大地を霧で覆うために……。'),
      mood('necros', 'normal'),
      say('necros', '気をつけよ。彼女は、封印の外から……もっと大きなものを、呼ぼうとしている。'),
      hide('necros'),
      bgm('victory'),
      fx('flash'),
      narr('王の姿が光となって消えると、天井から朝日が差し込んだ。'),
      bg('story/p-summer', 'in'),
      weather('motes'),
      show('liese', 'FL', 'glad'),
      say('liese', '霧が……！ 霧が、晴れていくわ！'),
      mood('alto', 'glad'),
      say('alto', 'やった……！ やったんだ、リーゼ！'),
      show('olden', 'R', 'normal', 'fade'),
      say('olden', 'ほっほ。見ておったぞ、アルト。りっぱな召喚士になったのう。'),
      say('alto', '師匠！ どうして、ここに！'),
      say('olden', '霧が晴れたので、飛んできたのじゃよ。……ところで。'),
      mood('olden', 'mad'),
      say('olden', '王の最期の言葉、聞こえたぞ。「影の女王」……やはり、そうか。'),
      mood('liese', 'normal'),
      say('liese', '先生、ご存じなのですか？ その女王のことを。'),
      say('olden', '知っておる。……千年前、冥府の王をそそのかし、大陸を闇に落とそうとした張本人じゃ。'),
      narr('そのとき、遠い北の空に、黒い塔の影が、ゆらりと浮かび上がった。'),
      bgm('boss'),
      weather('stars'),
      bg('story/p-shadows', 'in', { tint: 'rgba(40,20,70,1)' }),
      show('asha', 'C', 'normal', 'fade'),
      whisper('asha', '……よくぞ、王を倒してくれたわ。小さな召喚士。'),
      whisper('asha', '礼を言うわ。これで、私の「本当の扉」が開く。'),
      hide('asha'),
      title('第一部　完', '物語は、まだ終わらない……', 'TO BE CONTINUED'),
    ],
    lose: [
      bg('story/bones', 'in', { tint: 'rgba(60,70,120,1)' }),
      show('necros', 'C'),
      say('necros', '魂は……もらったぞ。……だが、まだ立てるのであろう？ 来い。'),
    ],
  },
];
