// 第5幕「辺境の軍勢」 — サリマ / ドルガン / ザルク / エルウィン / 影の女王
import { bg, bgm, choice, fx, hide, mood, narr, say, show, shout, sfx, title, wait, weather, whisper } from './dsl';
import type { Act, Chapter } from './types';

export const ACT5: Act = { no: 5, title: '辺境の軍勢', sub: '五つの旗、黒い塔へ', bg: 'story/landscape-desert' };

export const ACT5_CHAPTERS: Chapter[] = [
  // ------------------------------------------------------------------ 17 サリマ
  {
    id: 'c17',
    act: 5,
    rival: 'salima',
    title: '砂陽の試し',
    summary: '北の黒い塔を目指す途中、灼熱の砂漠で砂陽の民の戦士長サリマが行く手をふさぐ。',
    before: [
      bgm('menu'),
      title('第五幕　辺境の軍勢', '五つの旗、黒い塔へ', 'ACT V'),
      bg('story/landscape-desert', 'in'),
      weather('motes'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('霧が晴れて、季節がひとめぐりした。けれど、北の空の黒い塔は、日ごとに大きくなっていく。'),
      show('olden', 'C', 'normal', 'fade'),
      say('olden', '「影の女王」の塔は、いま「本当の扉」を開こうとしておる。扉が開けば、大陸の外から、さらに多くの闇が流れこむじゃろう。'),
      say('alto', 'それを止めるには？'),
      say('olden', '大陸の辺境に生きる、五つの民の力を借りるのじゃ。彼らの旗がそろえば、塔の結界は破れよう。'),
      say('liese', '最初の旗は、東の砂漠ね。……暑いわ。'),
      hide('olden'),
      narr('一行は、焼けつく砂丘を越えた。陽炎の向こうに、赤い旗がひるがえっている。'),
      sfx('horn-1', 0.5),
      show('salima', 'R', 'normal', 'fade'),
      say('salima', '止まれ、旅人。ここは砂陽の民の土地。理由なく入る者は、太陽に焼かれる。'),
      say('alto', 'ぼくはアルト。「影の女王」を止めるために、力を貸してほしくて来ました。'),
      say('salima', '……「影の女王」、か。その名は、わが一族の古い歌にもある。'),
      say('salima', 'だが、口先だけの者に旗は預けられぬ。わたしは戦士長サリマ。試させてもらう。'),
      choice('サリマに、どう答える？', [
        {
          label: '「望むところです」',
          then: [
            mood('alto', 'glad'),
            say('alto', '望むところです！ ぼくの仲間たちの強さ、見てください！'),
            say('salima', 'ふ……いい目をしている。'),
          ],
        },
        {
          label: '「争いたくはないけど……」',
          then: [
            mood('alto', 'worry'),
            say('alto', '争いたくはないけど……それで信じてもらえるなら、戦います。'),
            say('salima', '戦いは、言葉よりも多くを語る。それが砂の掟だ。'),
          ],
        },
      ]),
      mood('alto', 'normal'),
      bgm('battle3'),
      sfx('horn-3', 0.6),
      shout('salima', '砂陽の旗の下に！ いざ、尋常に！'),
    ],
    after: [
      bgm('menu'),
      bg('story/landscape-desert', 'in', { tint: 'rgba(255,200,130,1)' }),
      weather('motes'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'glad'),
      show('salima', 'R', 'normal'),
      say('salima', '……見事。砂の民は、強き者に旗を預ける。'),
      say('salima', '約束しよう。砂陽の戦士たちは、黒い塔の下へ駆けつける。'),
      mood('alto', 'glad'),
      say('alto', 'ありがとう、サリマさん！'),
      say('salima', '礼には及ばぬ。……ひとつ、忠告しておく。'),
      mood('salima', 'normal'),
      say('salima', '北の山のドワーフたちは、頑固だ。力を示さねば、扉すら開けてくれぬぞ。'),
      sfx('fanfare-short', 0.5),
      narr('サリマの赤い旗が、一行のかばんに、ひとつ結ばれた。'),
    ],
    lose: [
      bg('story/landscape-desert', 'in'),
      show('salima', 'C'),
      say('salima', '太陽はまだ、あなたを許してはいない。……もう一度、来るがいい。'),
    ],
  },

  // ------------------------------------------------------------------ 18 ドルガン
  {
    id: 'c18',
    act: 5,
    rival: 'dorgan',
    title: '鋼鉄の坑道',
    summary: '北の山脈。固く閉ざされた坑道の扉の前で、ドワーフの族長ドルガンが鉄槌を構える。',
    before: [
      bgm('menu'),
      bg('story/landscape-mountains-03', 'in'),
      weather('snow'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('北の山脈。吹きつける雪のなか、岩肌に巨大な鉄の扉が埋めこまれている。'),
      say('liese', 'ここが、ドワーフの坑道……。叩いても、びくともしないわ。'),
      sfx('mace', 0.5),
      narr('そのとき、扉の向こうから、地鳴りのような笑い声が響いた。'),
      sfx('rumble', 0.5),
      fx('quake'),
      show('dorgan', 'R', 'normal', 'rise'),
      shout('dorgan', 'ガハハハ！ 誰かと思えば、小さな召喚士じゃないか！'),
      say('dorgan', 'わしは坑道長ドルガン。この山の鉄は、わしらの誇りだ。気やすく扉を叩くでない！'),
      say('alto', 'お願いです、ドルガンさん。「影の女王」の塔を落とすために、ドワーフの力が必要なんです。'),
      say('dorgan', 'ふん、「影の女王」か。……千年前、わしらの祖先も、その闇に飲まれかけた。'),
      say('dorgan', 'だからこそ、見極めねばならん。お前にその鉄を預けていいかどうかを。'),
      bg('story/blacksmith', 'in'),
      weather('embers'),
      narr('ドルガンは、ふたりを坑道の奥の鍛冶場へ案内した。炉の火が、岩壁を赤く染めている。'),
      say('dorgan', '見ろ。この炉で鍛えたものは、千年たっても折れん。……お前の絆は、どうだ？'),
      choice('ドルガンの問いに、どう答える？', [
        {
          label: '「折れそうになったことは、何度もある」',
          then: [
            mood('alto', 'worry'),
            say('alto', '折れそうになったことは、何度もあります。でも、そのたびに誰かが支えてくれた。'),
            say('dorgan', 'ほう。鉄も、熱せられ、叩かれてこそ強くなる。……悪くない答えだ。'),
          ],
        },
        {
          label: '「折れたら、また鍛え直す！」',
          then: [
            mood('alto', 'glad'),
            say('alto', '折れたら、また鍛え直せばいい！ 何度でも！'),
            say('dorgan', 'ガハハ！ 気に入った！ 職人の言葉だ！'),
          ],
        },
      ]),
      mood('alto', 'normal'),
      bgm('battle3'),
      sfx('horn-3', 0.6),
      shout('dorgan', 'ならば、その絆、わしの鉄槌で確かめてくれるわ！'),
    ],
    after: [
      bgm('menu'),
      bg('story/blacksmith', 'in'),
      weather('embers'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'glad'),
      show('dorgan', 'R', 'normal'),
      say('dorgan', '……ふん、石頭のわしを割るとは。気に入った！'),
      sfx('mace', 0.6),
      narr('ドルガンが、鉄の大槌を床に打ちつけた。坑道じゅうに、高く澄んだ音が響きわたる。'),
      say('dorgan', 'いまの音は、全坑道への合図だ。ドワーフ一族は、黒い塔の下へ進軍する！'),
      mood('liese', 'glad'),
      say('liese', '心強いわ！ これで、二つ目の旗ね。'),
      say('dorgan', 'ただし。次のオークどもは、わしらよりずっと荒っぽいぞ。……まともに話が通じるかどうか。'),
      mood('alto', 'worry'),
      say('alto', 'オーク……。', 'worry'),
      sfx('fanfare-short', 0.5),
      narr('鉄の旗が、かばんのなかで、ずしりと重みを増した。'),
    ],
    lose: [
      bg('story/blacksmith', 'in'),
      show('dorgan', 'C'),
      say('dorgan', 'ガハハ、まだまだ鉄の熱が足りんな！ 出直してこい！'),
    ],
  },

  // ------------------------------------------------------------------ 19 ザルク
  {
    id: 'c19',
    act: 5,
    rival: 'zaluk',
    title: '蛮勇の大平原',
    summary: '荒野を埋めつくすオークの大軍。大王ザルクは、霧に飲まれずに、まだ吠えている。',
    before: [
      bgm('menu'),
      bg('story/landscape-battlefield_nohumans', 'in', { tint: 'rgba(200,120,80,1)' }),
      weather('ash'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('荒野を、見わたすかぎりのオークの軍旗が埋めつくしていた。地面が、いっせいの足踏みでふるえている。'),
      say('liese', 'すごい数……。これ全部が、ひとつの軍なの？'),
      sfx('horn-1', 0.6),
      show('garm', 'C', 'normal', 'fade'),
      say('garm', 'よう、小僧。久しぶりだな。'),
      mood('alto', 'glad'),
      say('alto', 'ガルム！ どうして、ここに？'),
      say('garm', '「影の女王」の囁きは、オークの谷にも届いた。だが、わしらの大王は、その声に頷かなかった。'),
      say('garm', '……問題は、その大王が、おまえたち人間を信じていない、ということだ。'),
      hide('garm'),
      shout('zaluk', 'グォォォ！ 人間の臭いがするぞォ！'),
      show('zaluk', 'R', 'normal', 'rise'),
      sfx('ugg', 0.6),
      fx('quake'),
      say('zaluk', 'わしは大王ザルク。オーク千の氏族を束ねる者。人間ごときが、わが軍の前に何の用だ！'),
      say('alto', 'ぼくたちは、あなたと戦いに来たんじゃない。「影の女王」を倒すために、力を……'),
      say('zaluk', 'うるさい！ 力を貸せだと？ 弱い者に、貸す力はない！'),
      say('zaluk', '強いと言うなら、見せてみろ。わが軍の足音のなかで、膝をつかずにいられたらな！'),
      choice('ザルクの咆哮に、どう立ち向かう？', [
        {
          label: '「膝はつかない。仲間がいるから」',
          then: [
            mood('alto', 'glad'),
            say('alto', '膝はつかない。ぼくには、一緒に戦ってくれる仲間がいるから！'),
            say('zaluk', 'グ……ハハ！ 群れを誇るか。オークと同じだな！'),
          ],
        },
        {
          label: '「ふるえてる。でも、逃げない」',
          then: [
            mood('alto', 'worry'),
            say('alto', '……正直、ふるえてます。でも、逃げません！'),
            say('zaluk', '正直な小僧だ。……嫌いではないぞ。'),
          ],
        },
      ]),
      mood('alto', 'normal'),
      bgm('battle3'),
      sfx('horn-3', 0.7),
      shout('zaluk', 'いくぞォ！ 全軍、突撃ィィィ！'),
    ],
    after: [
      bgm('menu'),
      bg('story/landscape-battlefield_nohumans', 'in', { tint: 'rgba(200,120,80,1)' }),
      weather('ash'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'glad'),
      show('zaluk', 'R', 'normal'),
      say('zaluk', 'グ……フ、フハハ！ 小さいくせに、よく吠える！'),
      say('zaluk', '認めよう、アルト。おまえの絆は、オークの軍勢に匹敵する！'),
      show('garm', 'C', 'normal', 'fade'),
      say('garm', '大王。……それでは？'),
      say('zaluk', 'うむ。オークの氏族は、すべて黒い塔へ進む。人間と、肩を並べてな！'),
      mood('alto', 'glad'),
      say('alto', 'ありがとう、ザルクさん！'),
      say('zaluk', '礼などいらん。……だが、エルフのやつらには、気をつけろ。あれは、わしらよりずっと頑固だぞ。'),
      sfx('fanfare-short', 0.5),
      narr('緑の旗の隣に、荒々しく染められた、オークの軍旗が結ばれた。'),
    ],
    lose: [
      bg('story/landscape-battlefield_nohumans', 'in', { tint: 'rgba(200,120,80,1)' }),
      show('zaluk', 'C'),
      say('zaluk', 'フハハ！ もう膝が笑っているぞ！ 立て、立てィ！'),
    ],
  },

  // ------------------------------------------------------------------ 20 エルウィン
  {
    id: 'c20',
    act: 5,
    rival: 'elwin',
    title: '大森林の王',
    summary: '千年の森。エルフの王エルウィンは、静かに剣を抜く。',
    before: [
      bgm('menu'),
      bg('story/p-black-forest', 'in', { tint: 'rgba(120,180,120,1)' }),
      weather('motes'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      narr('千年の森。霧のあとの森は、静かに息をふきかえしていた。梢の間から、光が降りそそぐ。'),
      say('liese', 'きれい……。でも、誰かに見られている気がするわ。'),
      sfx('magic-thorns-1', 0.4),
      show('elwin', 'R', 'normal', 'fade'),
      say('elwin', 'ようこそ、千年の森へ。わたしはエルウィン。この森を預かる者だ。'),
      say('elwin', '森はあなたを、ずっと見ていた。霧のなかを、ひるまず進んだ小さな召喚士を。'),
      say('alto', '……ぼくを、知っているんですか？'),
      say('elwin', '森は、すべてを覚えている。ティムの森も、フローラの墓所も、ヴェルドの古竜も。すべて、この森の根でつながっているのだ。'),
      bg('story/p-great-tree', 'in'),
      weather('motes'),
      narr('エルウィンは、ふたりを大樹の根もとへ導いた。幹には、千の年輪が刻まれている。'),
      say('elwin', '「影の女王」は、千年前にも、この大樹を倒そうとした。守りきったのは、わたしの先祖たちだ。'),
      say('elwin', 'だが、いまの人間は、あの頃より、ずっと脆い。……それでも、あなたは戦うというのか？'),
      choice('エルウィンの問いに、どう答える？', [
        {
          label: '「脆いからこそ、手をつなぐんです」',
          then: [
            mood('alto', 'glad'),
            say('alto', '脆いからこそ、手をつなぐんです。ひとりじゃ折れても、みんなでなら折れない。'),
            say('elwin', '……ふむ。ドルガンも、同じことを言ったのではないか？'),
            say('alto', 'えっ？ どうして、それを？'),
            say('elwin', '森は、すべてを覚えている、と言っただろう。'),
          ],
        },
        {
          label: '「ぼくは、ぼくにできることをするだけです」',
          then: [
            mood('alto', 'normal'),
            say('alto', 'ぼくは、ぼくにできることをするだけです。それが、みんなの力になると信じて。'),
            say('elwin', '飾らぬ言葉だ。……森も、そう言っている。'),
          ],
        },
      ]),
      mood('alto', 'normal'),
      say('elwin', 'あとは、剣と、カードで語ろう。……わが森の守りを、破れるか。'),
      bgm('battle3'),
      sfx('horn-3', 0.6),
      shout('elwin', '森よ、わたしに力を！ いざ！'),
    ],
    after: [
      bgm('menu'),
      bg('story/p-great-tree', 'in'),
      weather('motes'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'glad'),
      show('elwin', 'R', 'normal'),
      say('elwin', '……参りました。森も、あなたを認めたようだ。'),
      sfx('magic-holy-2', 0.5),
      narr('大樹の枝が、さわさわと揺れた。まるで、笑っているように。'),
      say('elwin', 'エルフの氏族は、黒い塔の麓へ進む。千年ぶりに、旗をひるがえそう。'),
      mood('liese', 'glad'),
      say('liese', 'これで、五つの旗がそろったのね！'),
      mood('elwin', 'normal'),
      say('elwin', 'いや。まだ、ひとつ足りない。……最後の旗は、あなたたち自身の旗だ。'),
      say('alto', 'ぼくたちの……旗？'),
      say('elwin', '行きなさい。その旗が、塔の最上階で、最後にひるがえるはずだ。'),
      sfx('fanfare-short', 0.5),
      narr('四つの旗が、風をはらんで、北の空へ向かって、はためいた。'),
    ],
    lose: [
      bg('story/p-great-tree', 'in'),
      show('elwin', 'C'),
      say('elwin', '焦ることはない。森は、待つことを知っている。……もう一度、おいで。'),
    ],
  },

  // ------------------------------------------------------------------ 21 影の女王
  {
    id: 'c21',
    act: 5,
    rival: 'asha',
    title: '影の玉座',
    summary: '黒い塔の最上階。千年の黒幕、影の女王との最後の戦い。',
    before: [
      bgm('menu'),
      bg('story/p-the-fall', 'in', { tint: 'rgba(80,60,120,1)' }),
      weather('storm'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('olden', 'C', 'normal'),
      narr('黒い塔の麓。五つの民の旗が、嵐のなかで、いっせいにはためいていた。'),
      sfx('horn-1', 0.6),
      say('olden', 'ここから先は、おまえたちだけで行くのじゃ。塔の外は、わしらが守る。'),
      mood('alto', 'worry'),
      say('alto', '師匠……。'),
      say('olden', '大丈夫じゃ。おまえは、もう立派な召喚士じゃよ。', 'teach'),
      mood('alto', 'glad'),
      say('liese', '行きましょう、アルト。最後まで、一緒よ。'),
      say('alto', 'うん！'),
      fx('fadeBlack'),
      wait(600),
      hide('olden'),
      bg('story/p-shadows', 'in', { tint: 'rgba(60,30,100,1)' }),
      weather('stars'),
      fx('unfade'),
      narr('塔の最上階。窓のない広間に、星のような光だけが、静かに浮かんでいる。'),
      bgm('boss'),
      show('asha', 'R', 'normal', 'fade'),
      whisper('asha', '……よく来たわね、小さな召喚士。この塔まで、本当に来るなんて。'),
      say('alto', '影の女王……！ ここで、あなたを止める！'),
      say('asha', '止める？ 私を？ ふふ……千年、誰にも止められなかったものを。'),
      say('liese', 'あなたの狙いは何なの？ 「本当の扉」を開いて、何をするつもり？'),
      say('asha', '決まっているでしょう。大陸のすべての魔獣と、絆を結び直すのよ。'),
      say('asha', 'ただし、「私」と。……人間と魔獣の絆なんて、脆くて、不公平。私なら、永遠の絆をあげられる。'),
      mood('alto', 'worry'),
      say('alto', '永遠の……絆？'),
      say('asha', '裏切られず、失われず、終わらない絆。……あなたも、欲しいでしょう？ 大切な誰かを、二度と失わない力が。'),
      choice('影の女王の誘いに、どう答える？', [
        {
          label: '「いらない。終わるから、大切なんだ」',
          then: [
            mood('alto', 'glad'),
            say('alto', 'いらない。終わりがあるから、いまが大切なんだ。ぼくは、そう教わったから。'),
            mood('asha', 'mad'),
            say('asha', '……あら。誰に、教わったのかしら。'),
            say('alto', '師匠と、仲間たちと、ぼくの……共に戦ってきた魔獣たちに！'),
          ],
        },
        {
          label: '「それは、絆じゃない。ただの鎖だ」',
          then: [
            mood('alto', 'mad'),
            say('alto', 'それは、絆じゃない。ただの、鎖だ！'),
            mood('asha', 'mad'),
            say('asha', '……鎖で、結構。逃げられるより、ずっといいわ。'),
          ],
        },
      ]),
      mood('alto', 'normal'),
      mood('asha', 'mad'),
      say('asha', '……そう。残念ね。ならば、あなたの絆ごと、闇に溶かしてあげましょう。'),
      fx('flash'),
      sfx('magic-dark-big', 0.8),
      fx('quake'),
      shout('asha', 'さあ、最後の勝負よ！ 影の玉座の前で、跪きなさい！'),
    ],
    after: [
      bgm('menu'),
      bg('story/p-shadows', 'in', { tint: 'rgba(60,30,100,1)' }),
      weather('stars'),
      show('alto', 'L', 'normal'),
      show('liese', 'FL', 'normal'),
      show('asha', 'R', 'defeated'),
      say('asha', '……ありえない。私の、千年が……！'),
      sfx('lich-die', 0.5),
      fx('flash'),
      narr('女王のまわりの闇が、ほどけるように薄れていく。星のような光が、ひとつ、またひとつと、窓のない広間から消えていった。'),
      mood('asha', 'normal'),
      say('asha', '……ずっと、ひとりだった。絆を結んだ魔獣たちは、みな、私より先に、いなくなってしまったから。'),
      mood('alto', 'worry'),
      say('alto', '……だから、「永遠」が欲しかったんですね。'),
      say('asha', '……ふふ。あなたの言うとおり。終わりがあるから、大切……なんて、千年経っても、私にはわからなかった。'),
      mood('liese', 'normal'),
      say('liese', '今から、わかればいいじゃない。……私たちみたいに。'),
      say('asha', '……生意気ね。'),
      hide('asha'),
      bgm('victory'),
      fx('flash'),
      narr('女王の姿が、光の粒となってほどけていく。黒い塔の壁が、ゆっくりと透きとおり、朝の光が差しこんだ。'),
      bg('story/p-summer', 'in'),
      weather('petals'),
      show('olden', 'R', 'normal', 'fade'),
      say('olden', 'やったな、アルト。……いや、大召喚士アルトよ。'),
      mood('alto', 'glad'),
      say('alto', 'みんなのおかげです。サリマさんも、ドルガンさんも、ザルクさんも、エルウィンさんも……。'),
      show('salima', 'FR', 'normal', 'fade'),
      say('salima', '砂陽の民は、あなたたちの旗とともに在る。'),
      narr('塔の下では、五つの旗が、朝の風に、ゆらゆらと揺れていた。'),
      mood('liese', 'glad'),
      say('liese', '帰りましょう、アルト。リーフェルの森へ。ティムが、待ってるわ。'),
      say('alto', 'うん！ ……みんなと、一緒に！'),
      title('ARCANE BEASTS', '大地アルカナ　— 完 —', 'FIN'),
    ],
    lose: [
      bg('story/p-shadows', 'in', { tint: 'rgba(60,30,100,1)' }),
      show('asha', 'C', 'normal'),
      whisper('asha', 'ふふ……もう、おしまい？ ……立ちなさい。あなたの絆は、まだ折れていないはず。'),
    ],
  },
];
