// 序章「黄昏のリーフェル」 — the festival, the old master, the twelve cards.
import { bars, bg, bgm, cg, choice, fx, hide, mood, narr, place, say, show, showCard, sfx, think, title, tone, wait, weather, whisper } from './dsl';
import type { Beat } from './types';

export const PROLOGUE: Beat[] = [
  bgm('legends'),
  bars(true),
  fx('fadeBlack'),
  wait(600),
  cg('story/p-statue', 'up'),
  fx('unfade'),
  wait(800),
  narr('むかし、ひとりの大魔導士が、十二枚のカードを描いた。'),
  narr('竜、海、森、雷、獣——どれも、この世にふたつとない絵だった。'),
  narr('魔導士は死の床で、こう言い残したという。'),
  narr('「十二枚を揃え、始まりの庭で掲げた者に、永遠を」'),
  narr('それから千年。十二枚は大陸じゅうに散り、伝説はおとぎ話になった。'),
  cg(null),
  bars(false),
  title('ARCANE BEASTS', '第一部　十二枚の伝説', 'PROLOGUE'),

  // ---------------------------------------------------------------- festival
  bgm('knolls'),
  bg('story/p-sunset-town', 'in', { tint: 'rgba(255,200,150,1)' }),
  weather('motes'),
  place('リーフェルの町', '夏至祭の夕暮れ'),
  sfx('fanfare-short', 0.5),
  narr('大陸の西のはずれ、麦畑に囲まれた小さな町、リーフェル。'),
  narr('年に一度の夏至祭。広場ではカードバトルの大会が開かれ、町じゅうが見物に集まっていた。'),
  show('hero', 'L', 'glad'),
  show('berta', 'R', 'normal', 'fade'),
  say('berta', '優勝おめでとう、{name}！ 三年連続だよ、三年連続！'),
  say('hero', 'ありがとう、ベルタさん。……でも、決勝は危なかった。'),
  say('berta', 'なに謙遜してんのさ。ほら、焼きたてだよ。オルデン先生のぶんも持っておいき。'),
  narr('ベルタは、まだ湯気の立つパンの包みを押しつけてきた。小麦と蜂蜜の、いつもの匂い。'),
  say('berta', '先生、最近は店も閉めがちだろう？ 咳もひどいし……ちゃんと食べさせてやるんだよ。'),
  mood('hero', 'worry'),
  say('hero', '……うん。'),
  hide('berta'),

  // ---------------------------------------------------------------- the shop
  bgm('transience'),
  bg('story/p-study', 'in', { tint: 'rgba(255,190,130,1)' }),
  weather('none'),
  place('オルデンのカード屋', '町はずれ'),
  narr('町はずれの、古いカード屋。棚には何十年ぶんものカードが、日焼けして並んでいる。'),
  show('hero', 'L', 'normal'),
  sfx('human-hit-1', 0.25),
  narr('奥から、乾いた咳が聞こえた。'),
  show('olden', 'R', 'normal', 'fade'),
  say('olden', 'おお……おかえり、{name}。窓から見ておったよ。見事な勝ちっぷりじゃった。'),
  say('hero', '先生、寝てなきゃだめだって。医者にも言われたでしょう。'),
  say('olden', 'ほっほ。医者はな、あと一年だと言いおった。……寝ていても、一年は一年じゃよ。', 'teach'),
  mood('hero', 'worry'),
  say('hero', '……そんなこと、言わないでください。'),
  narr('四十年前、大陸一と呼ばれたプレイヤー。それが、親のない子どもを拾って育てた、この老人だった。'),
  say('olden', '{name}。今日は、おまえに頼みがあってな。', 'normal'),
  sfx('open-chest', 0.6),
  narr('オルデンは、引き出しから一枚のカードを取り出した。黒ずんだ金の縁取り。燃えるような赤い竜。'),
  showCard('ヴォルカリオン', '伝説のカード　一枚目'),
  say('olden', '十二枚の伝説のカード。そのうちの一枚じゃ。若いころ、命がけで勝ち取った。'),
  say('hero', '伝説……って、あのおとぎ話の？'),
  say('olden', 'おとぎ話ではない。十二枚を揃えて「始まりの庭」で掲げれば、どんな病も消える霊薬が湧くという。'),
  say('olden', '……わしは、もう旅に出られん。だから、おまえに頼みたい。', 'teach'),
  say('olden', '残りの十一枚を、集めてきてくれんか。'),
  choice('師の頼みに、どう答える？', [
    {
      label: '「もちろん。先生のためなら」',
      then: [mood('hero', 'glad'), say('hero', 'もちろんです。先生のためなら、どこへでも行きます。'), say('olden', '……ありがとう。おまえは、昔からそうじゃった。', 'teach')],
    },
    {
      label: '「本当に、それで治るんですか」',
      then: [
        mood('hero', 'worry'),
        say('hero', '……本当に、それで治るんですか。'),
        say('olden', 'わからん。じゃが、わしにはもう、それしか残っておらんのじゃよ。'),
        say('hero', '……わかりました。行きます。'),
      ],
    },
  ]),
  say('olden', 'よいか、{name}。伝説のカードは、持ち主とバトルして勝ったときにだけ、譲り受けられる。それが古い掟じゃ。'),
  say('olden', '奪ってはならん。盗んでもならん。……勝って、手に入れるのじゃ。必ず、おまえの手でな。'),
  say('hero', 'はい。'),
  sfx('receive', 0.6),
  narr('オルデンは、赤い竜のカードを、{name}の手のひらにのせた。思っていたより、ずっと重かった。'),
  say('olden', 'これは、おまえが持っていけ。旅の最初の一枚じゃ。', 'teach'),
  say('olden', '残りは十一枚。……一枚ずつ、勝って増やしていけばよい。'),
  think('hero', '……先生の、一枚目。'),

  // ---------------------------------------------------------------- dawn
  bgm('journey'),
  fx('fadeBlack'),
  wait(700),
  bg('story/landscape-hills-01', 'right', { tint: 'rgba(255,215,170,1)' }),
  weather('motes'),
  fx('unfade'),
  place('リーフェルの外れ', '夜明け'),
  show('hero', 'L', 'normal'),
  narr('夜明け。麦畑の向こうに、町の屋根が小さく見えた。'),
  narr('祭りの飾りが、まだ風に揺れている。パン屋の煙突から、細い煙。'),
  say('hero', '……行ってきます。'),
  hide('hero'),
  wait(400),
  tone('cold'),
  bg('story/p-study', 'still', { tint: 'rgba(120,120,170,1)' }),
  bgm('shadows'),
  weather('none'),
  show('olden', 'C', 'normal', 'fade'),
  narr('誰もいなくなった店の奥で、老人は窓の外を見ていた。'),
  narr('咳は、もう出ていなかった。'),
  whisper('olden', '……行け。そして、勝ち続けろ。'),
  whisper('olden', '十二枚を、おまえの手で。'),
  mood('olden', 'mad'),
  fx('fadeBlackSlow'),
  hide('olden'),
  tone('none'),
  title('第一幕　旅立ち', '十二枚の伝説', 'ACT I'),
];
