import { bars, bg, bgm, choice, fx, hide, mood, narr, say, show, shout, sfx, title, wait, weather } from './dsl';
import type { Beat } from './types';

/** the very first scene: the village, the black star, the master's request */
export const PROLOGUE: Beat[] = [
  bgm('title'),
  bars(true),
  bg('story/p-great-tree', 'in'),
  weather('motes'),
  fx('fadeBlack'),
  wait(400),
  fx('unfade'),
  title('ARCANE BEASTS', '契約の大地アルカナ', 'PROLOGUE'),
  narr('人と魔獣が「契約」で結ばれ、ともに生きる大地——アルカナ。'),
  narr('その契約の証である一枚のカードが、人の勇気と魔獣の牙を、ひとつにつなぐ。'),
  bg('story/landscape-hills-01', 'right'),
  narr('大陸の西のはずれ、森に抱かれた小さな村リーフェル。'),
  narr('ここに、見習い召喚士の少年が暮らしていた。'),
  show('alto', 'L', 'glad'),
  say('alto', 'よーし、今日こそ師匠に一本とってやる！ 昨日ひらめいた新しいデッキで……'),
  bars(false),
  weather('none'),
  wait(300),
  bg('story/p-fog', 'in', { tint: 'rgba(120,120,160,1)' }),
  weather('fog'),
  bgm('menu'),
  mood('alto', 'worry'),
  say('alto', '……あれ？ 森が、静かすぎる。鳥の声がしない。'),
  sfx('rumble', 0.5),
  fx('quake'),
  show('olden', 'R', 'normal', 'fade'),
  say('olden', '気づいたか、アルト。ようやく目が育ってきたようじゃな。', 'teach'),
  say('alto', '師匠！ いまの揺れ……それにこの霧、ふつうの霧じゃない！'),
  say('olden', '黒い霧じゃ。北の果てから、少しずつ大陸を覆いはじめておる。'),
  say('olden', '霧に触れた魔獣は、契約を忘れ、ただ暴れるばかりになる。', 'mad'),
  mood('alto', 'normal'),
  say('alto', 'そんな……！ 村の森の仲間たちも？'),
  say('olden', '今はまだ無事じゃ。だが、いつまでもつかはわからぬ。', 'normal'),
  fx('fadeBlack'),
  wait(500),
  bg('story/p-study', 'in', { tint: 'rgba(255,220,170,1)' }),
  weather('motes'),
  fx('unfade'),
  say('olden', '千年前、この大地を覆った「冥府の王」の封印が、ほころびはじめておる。'),
  say('olden', '王の力に抗えるのは、強き召喚士たちの絆だけ。', 'teach'),
  say('olden', '大陸には、それぞれの地を守る強者たちがおる。彼らの力を借りるのじゃ。'),
  say('alto', 'でも、そんな人たちが、ぼくみたいな見習いの話を聞いてくれるかな……'),
  say('olden', 'ほっほ。だから「契約戦」があるのじゃよ。', 'normal'),
  say('olden', '召喚士は言葉より、デッキで語る。勝負して、認めさせるのじゃ。', 'teach'),
  choice('どうする？', [
    {
      label: 'やります！ 村とみんなを守りたい！',
      then: [mood('alto', 'glad'), shout('alto', 'やります！ 村も、森の仲間も、ぼくが守ります！'), say('olden', '……いい目じゃ。昔のわしによく似ておる。', 'normal')],
    },
    {
      label: 'こわい……でも、行くしかないですよね',
      then: [mood('alto', 'worry'), say('alto', 'こわい……でも、行くしかないですよね。'), say('olden', '怖いと言える者は強い。その気持ちを忘れるでないぞ。', 'teach')],
    },
  ]),
  mood('alto', 'normal'),
  say('olden', 'これを持っていくがよい。わしの旅の相棒たちじゃ。使い方は、もう教えてある。'),
  sfx('open-chest', 0.6),
  fx('flash'),
  narr('——アルトは、師匠から一組のデッキを受け取った。'),
  say('olden', '最初の相手は近くにおる。村の入り口で、おまえを待っておるぞ。'),
  say('alto', 'えっ、もう！？'),
  say('olden', 'ほっほ。旅は、思い立ったその日に始まるものじゃ。'),
  hide('olden'),
  mood('alto', 'glad'),
  say('alto', '……よし！ 行ってきます、師匠！'),
  hide('alto'),
  weather('none'),
];
